/*
 * aiqna db for web service (Blog Tables)
 * Database Name 'aiqna'
 *
 * Created 2024-09-24
 * Updated 2025-10-12
 */



/*
 ***********************************************************************************************
 * TABLE: blog_post_processing_logs (Blog Post Processing Logs)
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.blog_post_processing_logs (
    -- 증가형 PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- URL (유니크)
    blog_post_url VARCHAR(1023) NOT NULL UNIQUE,
    
    -- 메타데이터
    processing_status VARCHAR(20) DEFAULT 'pending',
    index_name VARCHAR(255),

    -- 불린 플래그들
    is_data_fetched BOOLEAN DEFAULT FALSE,
    is_pinecone_processed BOOLEAN DEFAULT FALSE,
    
    -- ERROR
    is_error_occurred BOOLEAN DEFAULT FALSE,
    error_message TEXT,

    -- 일시 정보
    processing_started TIMESTAMP WITH TIME ZONE,
    processing_completed TIMESTAMP WITH TIME ZONE,
    retry_count INTEGER DEFAULT 0,
    
    -- 시스템 타임스탬프
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_processed_at TIMESTAMP WITH TIME ZONE,

    source VARCHAR(50),
    priority INTEGER DEFAULT 5,
    assigned_worker VARCHAR(100),

    -- processing 상태 검증
    CONSTRAINT chk_blog_processing_status 
        CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),

    -- 시간 로직 검증
    CONSTRAINT chk_blog_processing_times 
        CHECK (
          processing_started IS NULL OR 
          processing_completed IS NULL OR 
          processing_completed >= processing_started
        ),

    -- 우선순위 검증
    CONSTRAINT chk_blog_priority CHECK (priority BETWEEN 1 AND 10)
);

-- 인덱스들
CREATE INDEX IF NOT EXISTS idx_blog_post_processing_logs_status 
    ON public.blog_post_processing_logs (processing_status);

CREATE INDEX IF NOT EXISTS idx_blog_post_processing_logs_priority 
    ON public.blog_post_processing_logs (priority)
    WHERE processing_status = 'pending';

CREATE INDEX IF NOT EXISTS idx_blog_post_processing_logs_error_flag
    ON public.blog_post_processing_logs (is_error_occurred)
    WHERE is_error_occurred = TRUE;

-- RLS
ALTER TABLE public.blog_post_processing_logs ENABLE ROW LEVEL SECURITY;

-- 읽기 전용 (모든 사용자)
CREATE POLICY "blog_post_processing_logs are visible to everyone" 
    ON public.blog_post_processing_logs
    FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

-- 관리 작업 (service_role만)
CREATE POLICY "Service role can manage blog_post_processing_logs" 
    ON public.blog_post_processing_logs
    FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- updated_at 자동 업데이트 트리거
-- (주의) update_updated_at_column() 함수가 사전에 존재해야 합니다.
CREATE TRIGGER trigger_update_blog_post_processing_logs_updated_at
    BEFORE UPDATE ON public.blog_post_processing_logs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();





/*
 ***********************************************************************************************
 * TABLE: blog_posts (Blog Posts)
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS blog_posts (
    -- 보조 유니크 UUID(36)
    uuid_36 VARCHAR(36) UNIQUE NOT NULL DEFAULT gen_random_uuid()::text,

    -- 기본 키
    blog_post_url VARCHAR(1023) PRIMARY KEY,
    
    title VARCHAR(1023),
    content TEXT,
    tags TEXT[],
    
    -- Open Graph 메타데이터
    og_title VARCHAR(1023),
    og_description VARCHAR(1023),
    og_image VARCHAR(2048),
    og_url VARCHAR(1023),
    
    local_image_url VARCHAR(511),

    platform VARCHAR(100),
    platform_url VARCHAR(1023),

    published_date TIMESTAMP WITH TIME ZONE,

    -- Summary From AI 
    info_country TEXT[],
    info_city TEXT[],
    info_district TEXT[],
    info_neighborhood TEXT[],
    info_landmark TEXT[],
    info_category TEXT[],
    info_name TEXT[],
    info_special_tag TEXT[],
    info_influencer TEXT[],
    info_season TEXT[],
    info_time_of_day TEXT[],
    info_activity_type TEXT[],
    info_reservation_required BOOLEAN,
    info_travel_tips TEXT[],

    -- 시스템 타임스탬프
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_processed_at TIMESTAMP WITH TIME ZONE,

    metadata_json JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 기본 인덱스
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_date 
    ON blog_posts(published_date);
CREATE INDEX IF NOT EXISTS idx_blog_posts_platform 
    ON blog_posts(platform);
CREATE INDEX IF NOT EXISTS idx_blog_posts_is_active 
    ON blog_posts(is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_blog_posts_is_deleted 
    ON blog_posts(is_deleted) WHERE is_deleted = FALSE;

-- 배열 컬럼 GIN 인덱스
CREATE INDEX IF NOT EXISTS idx_blog_posts_tags_gin 
    ON blog_posts USING gin(tags);

-- 전체 텍스트 검색 인덱스
CREATE INDEX IF NOT EXISTS idx_blog_posts_text_search_gin 
    ON blog_posts USING gin(to_tsvector('simple', 
    COALESCE(title, '') || ' ' || 
    COALESCE(og_title, '') || ' ' || 
    COALESCE(content, '')));

-- JSONB 인덱스
CREATE INDEX IF NOT EXISTS idx_blog_posts_metadata_json_gin 
    ON blog_posts USING gin(metadata_json);

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- 읽기 전용
CREATE POLICY "blog_posts are visible to everyone" 
    ON blog_posts FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

-- 관리 작업
CREATE POLICY "Service role can manage blog_posts" 
    ON blog_posts FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- updated_at 자동 업데이트 트리거
CREATE TRIGGER trigger_update_blog_posts_updated_at
    BEFORE UPDATE ON blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

