/*
 * aiqna db for web service (Google Places and Mapping Tables)
 * Database Name 'aiqna'
 *
 * Created 2024-10-12
 * Updated 2025-12-07
 * 
 * 테이블:
 *   1. google_place            - Google Places API 데이터
 *   2. map_google_place        - 콘텐츠-장소 매핑
 * 
 * 함수:
 *   - upsert_google_place_data()         - 장소 데이터 저장
 *   - upsert_google_place_mapping()      - 콘텐츠-장소 매핑 저장
 *   - get_google_places_for_content()    - 콘텐츠의 장소 목록 조회
 *   - get_content_for_google_place()     - 장소의 콘텐츠 목록 조회
 *   - get_google_places_by_location()    - 지역별 장소 조회
 */


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                          1. GOOGLE_PLACE 테이블                            ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: google_place
 ***********************************************************************************************
 * 설명: Google Places API (New) 데이터 저장
 * 데이터 소스: Google Places API v1
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.google_place (
    -- ========================================
    -- 기본 키 및 식별자
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_place_id VARCHAR(255) NOT NULL,      -- Google Place ID (ChIJ...)
    resource_name TEXT NULL,                    -- places/{place_id} 형식
    
    -- ========================================
    -- 지역 연결 (FK)
    -- ========================================
    country_code VARCHAR(2) NOT NULL DEFAULT 'AA',
    city_code VARCHAR(96) NULL,
    district_code VARCHAR(96) NULL,
    
    -- ========================================
    -- 이름 및 설명
    -- ========================================
    display_name TEXT NOT NULL,                  -- displayName.text
    display_name_lang VARCHAR(10) NULL,          -- displayName.languageCode
    
    -- 다국어 이름 (커스텀)
    name_en TEXT NULL,
    name_native TEXT NULL,
    name_ko TEXT NULL,
    
    -- editorialSummary (LocalizedText)
    editorial_summary TEXT NULL,                 -- editorialSummary.text
    editorial_summary_lang VARCHAR(10) NULL,     -- editorialSummary.languageCode
    
    -- generativeSummary (AI 생성)
    generative_summary TEXT NULL,                -- generativeSummary.overview.text
    generative_summary_lang VARCHAR(10) NULL,
    
    -- reviewSummary (AI 생성)
    review_summary TEXT NULL,                    -- reviewSummary.text.text
    review_summary_lang VARCHAR(10) NULL,
    
    -- neighborhoodSummary (AI 생성)
    neighborhood_summary TEXT NULL,              -- neighborhoodSummary.overview.text
    
    -- ========================================
    -- 분류 정보
    -- ========================================
    types TEXT[] NULL,                           -- types[] 배열
    primary_type VARCHAR(127) NULL,              -- primaryType
    primary_type_display_name TEXT NULL,         -- primaryTypeDisplayName.text
    
    -- ========================================
    -- 주소 정보
    -- ========================================
    formatted_address TEXT NULL,
    short_formatted_address TEXT NULL,           -- shortFormattedAddress
    adr_format_address TEXT NULL,                -- adrFormatAddress (HTML 형식)
    
    -- postalAddress
    postal_region_code VARCHAR(10) NULL,         -- postalAddress.regionCode
    postal_language_code VARCHAR(10) NULL,       -- postalAddress.languageCode
    postal_code VARCHAR(20) NULL,                -- postalAddress.postalCode
    administrative_area TEXT NULL,               -- postalAddress.administrativeArea (시/도)
    locality TEXT NULL,                          -- postalAddress.locality (시/군/구)
    sublocality TEXT NULL,                       -- postalAddress.sublocality (동/읍/면)
    address_lines TEXT[] NULL,                   -- postalAddress.addressLines[]
    
    -- addressComponents (JSONB로 저장)
    address_components JSONB NULL,
    
    -- plusCode
    plus_code_global VARCHAR(20) NULL,           -- plusCode.globalCode
    plus_code_compound VARCHAR(100) NULL,        -- plusCode.compoundCode
    
    -- ========================================
    -- 연락처
    -- ========================================
    national_phone_number VARCHAR(30) NULL,      -- nationalPhoneNumber
    international_phone_number VARCHAR(30) NULL, -- internationalPhoneNumber
    website_uri TEXT NULL,                       -- websiteUri
    
    -- ========================================
    -- 위치 정보
    -- ========================================
    latitude NUMERIC(10,7) NULL,                 -- location.latitude
    longitude NUMERIC(10,7) NULL,                -- location.longitude
    
    -- 자동 생성 지리 객체 (PostGIS)
    location_point GEOGRAPHY(POINT, 4326)
        GENERATED ALWAYS AS (
            CASE 
                WHEN latitude IS NOT NULL AND longitude IS NOT NULL 
                THEN geography(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326))
                ELSE NULL
            END
        ) STORED,
    
    -- viewport (Viewport)
    viewport_low_lat NUMERIC(10,7) NULL,         -- viewport.low.latitude
    viewport_low_lng NUMERIC(10,7) NULL,         -- viewport.low.longitude
    viewport_high_lat NUMERIC(10,7) NULL,        -- viewport.high.latitude
    viewport_high_lng NUMERIC(10,7) NULL,        -- viewport.high.longitude
    
    -- ========================================
    -- 시간대
    -- ========================================
    utc_offset_minutes SMALLINT NULL,            -- utcOffsetMinutes
    timezone_id VARCHAR(63) NULL,                -- timeZone.id
    timezone_version VARCHAR(20) NULL,           -- timeZone.version
    
    -- ========================================
    -- 평점 및 리뷰
    -- ========================================
    rating NUMERIC(2,1) NULL,                    -- rating (1.0 ~ 5.0)
    user_rating_count INTEGER NULL,              -- userRatingCount
    reviews JSONB NULL,                          -- reviews[] (최대 5개)
    
    -- ========================================
    -- 영업 상태
    -- ========================================
    business_status VARCHAR(30) NULL,            -- OPERATIONAL, ...
    
    -- ========================================
    -- 영업 시간
    -- ========================================
    opening_hours_periods JSONB NULL,               -- regularOpeningHours.periods[]
    opening_hours_weekday_descriptions JSONB NULL,  -- regularOpeningHours.weekdayDescriptions[]
    current_opening_hours JSONB NULL,
    secondary_opening_hours JSONB NULL,
    
    -- ========================================
    -- 사진
    -- ========================================
    photos JSONB NULL,                           -- photos[] (최대 10개)
    
    -- ========================================
    -- 가격 정보
    -- ========================================
    price_level VARCHAR(30) NULL,                -- priceLevel
    price_range_start_currency VARCHAR(3) NULL,
    price_range_start_units BIGINT NULL,
    price_range_start_nanos INTEGER NULL,
    price_range_end_currency VARCHAR(3) NULL,
    price_range_end_units BIGINT NULL,
    price_range_end_nanos INTEGER NULL,
    
    -- ========================================
    -- 결제 옵션 (paymentOptions)
    -- ========================================
    accepts_credit_cards BOOLEAN NULL,
    accepts_debit_cards BOOLEAN NULL,
    accepts_cash_only BOOLEAN NULL,
    accepts_nfc BOOLEAN NULL,
    
    -- ========================================
    -- 주차 옵션 (parkingOptions)
    -- ========================================
    free_parking_lot BOOLEAN NULL,
    paid_parking_lot BOOLEAN NULL,
    free_street_parking BOOLEAN NULL,
    paid_street_parking BOOLEAN NULL,
    valet_parking BOOLEAN NULL,
    free_garage_parking BOOLEAN NULL,
    paid_garage_parking BOOLEAN NULL,
    
    -- ========================================
    -- 서비스 옵션
    -- ========================================
    takeout BOOLEAN NULL,
    delivery BOOLEAN NULL,
    dine_in BOOLEAN NULL,
    curbside_pickup BOOLEAN NULL,
    reservable BOOLEAN NULL,
    outdoor_seating BOOLEAN NULL,
    live_music BOOLEAN NULL,
    menu_for_children BOOLEAN NULL,
    restroom BOOLEAN NULL,
    
    -- ========================================
    -- 음식 및 음료 (serves*)
    -- ========================================
    serves_breakfast BOOLEAN NULL,
    serves_lunch BOOLEAN NULL,
    serves_dinner BOOLEAN NULL,
    serves_brunch BOOLEAN NULL,
    serves_beer BOOLEAN NULL,
    serves_wine BOOLEAN NULL,
    serves_cocktails BOOLEAN NULL,
    serves_coffee BOOLEAN NULL,
    serves_dessert BOOLEAN NULL,
    serves_vegetarian_food BOOLEAN NULL,
    
    -- ========================================
    -- 분위기 및 특성
    -- ========================================
    good_for_children BOOLEAN NULL,
    good_for_groups BOOLEAN NULL,
    good_for_watching_sports BOOLEAN NULL,
    allows_dogs BOOLEAN NULL,
    
    -- ========================================
    -- 접근성
    -- ========================================
    wheelchair_accessible_parking BOOLEAN NULL,
    wheelchair_accessible_entrance BOOLEAN NULL,
    wheelchair_accessible_restroom BOOLEAN NULL,
    wheelchair_accessible_seating BOOLEAN NULL,
    
    -- ========================================
    -- Google Maps 링크
    -- ========================================
    google_maps_uri TEXT NULL,
    google_maps_directions_uri TEXT NULL,
    google_maps_place_uri TEXT NULL,
    google_maps_reviews_uri TEXT NULL,
    google_maps_photos_uri TEXT NULL,
    google_maps_write_review_uri TEXT NULL,
    
    -- ========================================
    -- 기타 정보
    -- ========================================
    sub_destinations JSONB NULL,
    containing_places JSONB NULL,
    address_descriptor JSONB NULL,
    attributions JSONB NULL,
    icon_mask_base_uri TEXT NULL,
    icon_background_color VARCHAR(7) NULL,
    pure_service_area_business BOOLEAN NULL,
    moved_place_resource_name TEXT NULL,
    moved_place_id VARCHAR(255) NULL,
    
    -- ========================================
    -- EV 충전
    -- ========================================
    ev_connector_count INTEGER NULL,
    ev_connector_aggregation JSONB NULL,
    ev_charge_amenity_summary JSONB NULL,
    
    -- ========================================
    -- 주유소
    -- ========================================
    fuel_prices JSONB NULL,
    
    -- ========================================
    -- 경고
    -- ========================================
    consumer_alert JSONB NULL,
    
    -- ========================================
    -- 커스텀 필드: 외부 링크
    -- ========================================
    naver_map_url TEXT NULL,
    instagram_id VARCHAR(50) NULL,
    youtube_channel_id VARCHAR(30) NULL,
    trip_advisor_url TEXT NULL,
    facebook_url TEXT NULL,
    
    -- ========================================
    -- 커스텀 필드: 타겟 그룹
    -- ========================================
    is_target_for_family BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_children BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_couple BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_friends BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_solo BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- ========================================
    -- 커스텀 필드: 소요 시간 (분)
    -- ========================================
    taking_minutes_min SMALLINT NULL,
    taking_minutes_max SMALLINT NULL,
    
    -- ========================================
    -- 커스텀 필드: 운영 기간
    -- ========================================
    is_open_always BOOLEAN NOT NULL DEFAULT TRUE,
    period_start DATE NULL,
    period_end DATE NULL,
    
    -- ========================================
    -- 시스템 관리
    -- ========================================
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_display BOOLEAN NOT NULL DEFAULT TRUE,
    fetched_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT gp_google_place_id_unique 
        UNIQUE (google_place_id),
    
    CONSTRAINT gp_country_code_fkey
        FOREIGN KEY (country_code)
        REFERENCES public.countries (country_code)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT gp_city_code_fkey
        FOREIGN KEY (city_code)
        REFERENCES public.cities (city_code)
        ON UPDATE CASCADE ON DELETE SET NULL,
    
    CONSTRAINT gp_district_code_fkey
        FOREIGN KEY (district_code)
        REFERENCES public.districts (district_code)
        ON UPDATE CASCADE ON DELETE SET NULL,
    
    CONSTRAINT gp_rating_check 
        CHECK (rating IS NULL OR (rating >= 1.0 AND rating <= 5.0)),
    
    CONSTRAINT gp_user_rating_count_check 
        CHECK (user_rating_count IS NULL OR user_rating_count >= 0),
    
    CONSTRAINT gp_latitude_check 
        CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
    
    CONSTRAINT gp_longitude_check 
        CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
    
    CONSTRAINT gp_viewport_check 
        CHECK (
            (viewport_low_lat IS NULL AND viewport_low_lng IS NULL 
            AND viewport_high_lat IS NULL AND viewport_high_lng IS NULL)
            OR
            (viewport_low_lat IS NOT NULL AND viewport_low_lng IS NOT NULL
            AND viewport_high_lat IS NOT NULL AND viewport_high_lng IS NOT NULL
            AND viewport_low_lat BETWEEN -90 AND 90
            AND viewport_high_lat BETWEEN -90 AND 90
            AND viewport_low_lng BETWEEN -180 AND 180
            AND viewport_high_lng BETWEEN -180 AND 180)
        ),
    
    CONSTRAINT gp_utc_offset_check 
        CHECK (utc_offset_minutes IS NULL OR (utc_offset_minutes BETWEEN -720 AND 840)),
    
    CONSTRAINT gp_business_status_check
        CHECK (business_status IS NULL OR business_status IN 
                ('OPERATIONAL', 'CLOSED_TEMPORARILY', 'CLOSED_PERMANENTLY')),
    
    CONSTRAINT gp_price_level_check
        CHECK (price_level IS NULL OR price_level IN 
                ('PRICE_LEVEL_FREE',
                'PRICE_LEVEL_INEXPENSIVE',
                'PRICE_LEVEL_MODERATE',
                'PRICE_LEVEL_EXPENSIVE',
                'PRICE_LEVEL_VERY_EXPENSIVE')),
    
    CONSTRAINT gp_price_range_check
        CHECK (
            (price_range_start_currency IS NULL 
            AND price_range_start_units IS NULL 
            AND price_range_start_nanos IS NULL
            AND price_range_end_currency IS NULL
            AND price_range_end_units IS NULL
            AND price_range_end_nanos IS NULL)
            OR
            (price_range_start_currency IS NOT NULL
            AND price_range_end_currency IS NOT NULL
            AND price_range_start_currency = price_range_end_currency)
        ),
    
    CONSTRAINT gp_ev_connector_count_check
        CHECK (ev_connector_count IS NULL OR ev_connector_count >= 0),
    
    CONSTRAINT gp_icon_bg_color_check
        CHECK (icon_background_color IS NULL OR icon_background_color ~ '^#[0-9A-Fa-f]{6}$'),
    
    CONSTRAINT gp_taking_minutes_check 
        CHECK (
            (taking_minutes_min IS NULL AND taking_minutes_max IS NULL)
            OR
            (taking_minutes_min IS NOT NULL AND taking_minutes_max IS NOT NULL 
            AND taking_minutes_min > 0 AND taking_minutes_max > 0
            AND taking_minutes_min <= taking_minutes_max)
        ),
    
    CONSTRAINT gp_period_check 
        CHECK (
            is_open_always = TRUE
            OR
            (period_start IS NOT NULL AND period_end IS NOT NULL 
            AND period_start <= period_end)
        )
);

-- ========================================
-- 인덱스: google_place
-- ========================================
-- 기본 검색 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_google_place_id 
    ON public.google_place (google_place_id);

CREATE INDEX IF NOT EXISTS idx_gp_country_code 
    ON public.google_place (country_code);

CREATE INDEX IF NOT EXISTS idx_gp_city_code 
    ON public.google_place (city_code) 
    WHERE city_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_district_code 
    ON public.google_place (district_code) 
    WHERE district_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_primary_type 
    ON public.google_place (primary_type) 
    WHERE primary_type IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_types_gin 
    ON public.google_place USING GIN (types);

CREATE INDEX IF NOT EXISTS idx_gp_rating 
    ON public.google_place (rating DESC NULLS LAST, user_rating_count DESC NULLS LAST) 
    WHERE rating IS NOT NULL;

-- 위치 인덱스 (PostGIS)
CREATE INDEX IF NOT EXISTS idx_gp_location_gist 
    ON public.google_place USING GIST (location_point) 
    WHERE location_point IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_lat_lng 
    ON public.google_place (latitude, longitude) 
    WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

-- 텍스트 검색 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_display_name_trgm 
    ON public.google_place USING GIN (display_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_gp_name_ko_trgm 
    ON public.google_place USING GIN (name_ko gin_trgm_ops) 
    WHERE name_ko IS NOT NULL;

-- 활성화 상태 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_is_active 
    ON public.google_place (is_active, is_display) 
    WHERE is_active = TRUE AND is_display = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_business_status 
    ON public.google_place (business_status) 
    WHERE business_status IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_price_level 
    ON public.google_place (price_level) 
    WHERE price_level IS NOT NULL;

-- 타겟 그룹 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_target_family 
    ON public.google_place (is_target_for_family) 
    WHERE is_target_for_family = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_target_couple 
    ON public.google_place (is_target_for_couple) 
    WHERE is_target_for_couple = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_target_children 
    ON public.google_place (is_target_for_children) 
    WHERE is_target_for_children = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_target_friends 
    ON public.google_place (is_target_for_friends) 
    WHERE is_target_for_friends = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_target_solo 
    ON public.google_place (is_target_for_solo) 
    WHERE is_target_for_solo = TRUE;

-- 서비스 옵션 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_delivery 
    ON public.google_place (delivery) 
    WHERE delivery = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_reservable 
    ON public.google_place (reservable) 
    WHERE reservable = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_outdoor_seating 
    ON public.google_place (outdoor_seating) 
    WHERE outdoor_seating = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_serves_vegetarian 
    ON public.google_place (serves_vegetarian_food) 
    WHERE serves_vegetarian_food = TRUE;

-- 접근성 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_wheelchair_accessible 
    ON public.google_place (wheelchair_accessible_entrance) 
    WHERE wheelchair_accessible_entrance = TRUE;

CREATE INDEX IF NOT EXISTS idx_gp_good_for_children 
    ON public.google_place (good_for_children) 
    WHERE good_for_children = TRUE;

-- 시간 인덱스
CREATE INDEX IF NOT EXISTS idx_gp_fetched_at 
    ON public.google_place (fetched_at NULLS FIRST);

CREATE INDEX IF NOT EXISTS idx_gp_recently_fetched 
    ON public.google_place (fetched_at DESC) 
    WHERE fetched_at > NOW() - INTERVAL '30 days';

-- JSONB 인덱스 (jsonb_path_ops 사용으로 성능 향상)
CREATE INDEX IF NOT EXISTS idx_gp_photos_gin 
    ON public.google_place USING GIN (photos jsonb_path_ops) 
    WHERE photos IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_reviews_gin 
    ON public.google_place USING GIN (reviews jsonb_path_ops) 
    WHERE reviews IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_opening_hours_gin
    ON public.google_place USING GIN (opening_hours_periods jsonb_path_ops)
    WHERE opening_hours_periods IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_address_components_gin
    ON public.google_place USING GIN (address_components jsonb_path_ops)
    WHERE address_components IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_sub_destinations_gin
    ON public.google_place USING GIN (sub_destinations jsonb_path_ops)
    WHERE sub_destinations IS NOT NULL;

-- 복합 인덱스 (자주 함께 사용되는 조합)
CREATE INDEX IF NOT EXISTS idx_gp_city_type 
    ON public.google_place (city_code, primary_type) 
    WHERE city_code IS NOT NULL AND primary_type IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_city_rating 
    ON public.google_place (city_code, rating DESC NULLS LAST) 
    WHERE city_code IS NOT NULL AND rating IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gp_type_rating 
    ON public.google_place (primary_type, rating DESC NULLS LAST) 
    WHERE primary_type IS NOT NULL AND rating IS NOT NULL;

-- 인기 장소 인덱스 (리뷰 많고 평점 높은 장소)
CREATE INDEX IF NOT EXISTS idx_gp_popular_places 
    ON public.google_place (user_rating_count DESC, rating DESC) 
    WHERE user_rating_count > 100 AND rating >= 4.0;

-- ========================================
-- RLS: google_place
-- ========================================
ALTER TABLE public.google_place ENABLE ROW LEVEL SECURITY;

CREATE POLICY "google_place is visible to everyone"
    ON public.google_place FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage google_place"
    ON public.google_place FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: google_place updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION public.update_google_place_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_gp_updated_at
    BEFORE UPDATE ON public.google_place
    FOR EACH ROW
    EXECUTE FUNCTION public.update_google_place_updated_at();

-- ========================================
-- 트리거: location_point 검증
-- ========================================
CREATE OR REPLACE FUNCTION public.check_google_place_location()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- 위도/경도는 있는데 location_point가 NULL인 경우 경고
    IF NEW.latitude IS NOT NULL 
        AND NEW.longitude IS NOT NULL 
        AND NEW.location_point IS NULL THEN
        RAISE WARNING 'location_point is NULL despite having lat/lng for place_id: %', NEW.google_place_id;
    END IF;
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_gp_check_location
    BEFORE INSERT OR UPDATE ON public.google_place
    FOR EACH ROW
    EXECUTE FUNCTION public.check_google_place_location();




-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                         2. MAP_GOOGLE_PLACE 테이블                         ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: map_google_place
 ***********************************************************************************************
 * 설명: AI로 추출된 Google Place와 콘텐츠 매핑
 * source_type: youtube_video, instagram_post, blog_post, text_content
 * 
 * 특징:
 *   - 타입별 전용 ID 컬럼 사용 (타입 안정성 & FK 제약)
 *   - 하나의 source_type당 정확히 하나의 ID만 NOT NULL
 *   - 각 콘텐츠 테이블에 대한 FK 제약으로 참조 무결성 보장
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.map_google_place (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    
    -- ========================================
    -- 매핑 정보
    -- ========================================
    google_place_id VARCHAR(255) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    
    -- 타입별 ID (source_type에 따라 하나만 NOT NULL)
    youtube_video_id VARCHAR(20) NULL,
    instagram_post_id VARCHAR(50) NULL,
    blog_post_id BIGINT NULL,
    text_content_id BIGINT NULL,
    
    -- ========================================
    -- AI 추출 정보
    -- ========================================
    confidence_score NUMERIC(3,2) NULL,
    extraction_method VARCHAR(50) NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- ========================================
    -- 검증 정보
    -- ========================================
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMPTZ NULL,
    verified_by VARCHAR(255) NULL,
    
    -- ========================================
    -- 표시 순서
    -- ========================================
    is_selected BOOLEAN NOT NULL DEFAULT FALSE,
    order_num INTEGER NOT NULL DEFAULT 0,
    
    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT mgp_google_place_id_fkey
        FOREIGN KEY (google_place_id) 
        REFERENCES public.google_place (google_place_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT mgp_youtube_video_id_fkey
        FOREIGN KEY (youtube_video_id) 
        REFERENCES public.youtube_video (video_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT mgp_instagram_post_id_fkey
        FOREIGN KEY (instagram_post_id) 
        REFERENCES public.instagram_post (post_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT mgp_blog_post_id_fkey
        FOREIGN KEY (blog_post_id) 
        REFERENCES public.blog_post (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT mgp_text_content_id_fkey
        FOREIGN KEY (text_content_id) 
        REFERENCES public.text_content (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT mgp_source_type_check 
        CHECK (source_type IN ('youtube_video', 'instagram_post', 'blog_post', 'text_content')),
    
    CONSTRAINT mgp_one_source_id_check 
        CHECK (
            (source_type = 'youtube_video' 
            AND youtube_video_id IS NOT NULL 
            AND instagram_post_id IS NULL 
            AND blog_post_id IS NULL 
            AND text_content_id IS NULL)
            OR
            (source_type = 'instagram_post' 
            AND instagram_post_id IS NOT NULL 
            AND youtube_video_id IS NULL 
            AND blog_post_id IS NULL 
            AND text_content_id IS NULL)
            OR
            (source_type = 'blog_post' 
            AND blog_post_id IS NOT NULL 
            AND youtube_video_id IS NULL 
            AND instagram_post_id IS NULL 
            AND text_content_id IS NULL)
            OR
            (source_type = 'text_content' 
            AND text_content_id IS NOT NULL 
            AND youtube_video_id IS NULL 
            AND instagram_post_id IS NULL 
            AND blog_post_id IS NULL)
        ),
    
    CONSTRAINT mgp_mapping_unique 
        UNIQUE (google_place_id, source_type, 
                COALESCE(youtube_video_id, 
                        instagram_post_id, 
                        blog_post_id::TEXT, 
                        text_content_id::TEXT)),
    
    CONSTRAINT mgp_order_num_check 
        CHECK (order_num >= 0),
    
    CONSTRAINT mgp_confidence_check 
        CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)),
    
    CONSTRAINT mgp_verified_logic_check
        CHECK (
            (is_verified = FALSE AND verified_at IS NULL AND verified_by IS NULL)
            OR
            (is_verified = TRUE AND verified_at IS NOT NULL)
        )
);

-- ========================================
-- 인덱스: map_google_place
-- ========================================
-- 기본 매핑 인덱스
CREATE INDEX IF NOT EXISTS idx_mgp_place_order 
    ON public.map_google_place (google_place_id, order_num);

CREATE INDEX IF NOT EXISTS idx_mgp_place_added 
    ON public.map_google_place (google_place_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mgp_selected 
    ON public.map_google_place (google_place_id, order_num) 
    WHERE is_selected = TRUE;

CREATE INDEX IF NOT EXISTS idx_mgp_verified 
    ON public.map_google_place (google_place_id, confidence_score DESC) 
    WHERE is_verified = TRUE;

-- 소스별 인덱스
CREATE INDEX IF NOT EXISTS idx_mgp_youtube_video 
    ON public.map_google_place (youtube_video_id, google_place_id) 
    WHERE youtube_video_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mgp_instagram_post 
    ON public.map_google_place (instagram_post_id, google_place_id) 
    WHERE instagram_post_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mgp_blog_post 
    ON public.map_google_place (blog_post_id, google_place_id) 
    WHERE blog_post_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mgp_text_content 
    ON public.map_google_place (text_content_id, google_place_id) 
    WHERE text_content_id IS NOT NULL;

-- 소스 타입별 인덱스
CREATE INDEX IF NOT EXISTS idx_mgp_source_type 
    ON public.map_google_place (source_type, created_at DESC);

-- 신뢰도 인덱스
CREATE INDEX IF NOT EXISTS idx_mgp_high_confidence 
    ON public.map_google_place (confidence_score DESC) 
    WHERE confidence_score >= 0.8;

CREATE INDEX IF NOT EXISTS idx_mgp_low_confidence 
    ON public.map_google_place (confidence_score ASC) 
    WHERE confidence_score < 0.7 AND is_verified = FALSE;

-- 추출 방법 인덱스
CREATE INDEX IF NOT EXISTS idx_mgp_extraction_method 
    ON public.map_google_place (extraction_method) 
    WHERE extraction_method IS NOT NULL;

-- 최근 추출 인덱스
CREATE INDEX IF NOT EXISTS idx_mgp_recently_extracted 
    ON public.map_google_place (extracted_at DESC) 
    WHERE extracted_at > NOW() - INTERVAL '7 days';

-- ========================================
-- RLS: map_google_place
-- ========================================
ALTER TABLE public.map_google_place ENABLE ROW LEVEL SECURITY;

CREATE POLICY "map_google_place is visible to everyone"
    ON public.map_google_place FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage map_google_place"
    ON public.map_google_place FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: map_google_place updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION public.update_map_google_place_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_mgp_updated_at
    BEFORE UPDATE ON public.map_google_place
    FOR EACH ROW
    EXECUTE FUNCTION public.update_map_google_place_updated_at();

-- ========================================
-- 트리거: order_num 자동 관리
-- ========================================
CREATE OR REPLACE FUNCTION public.auto_assign_order_num()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_max_order INTEGER;
    v_source_id TEXT;
BEGIN
    -- source_id 추출 (타입에 따라)
    v_source_id := CASE NEW.source_type
        WHEN 'youtube_video' THEN NEW.youtube_video_id
        WHEN 'instagram_post' THEN NEW.instagram_post_id
        WHEN 'blog_post' THEN NEW.blog_post_id::TEXT
        WHEN 'text_content' THEN NEW.text_content_id::TEXT
    END;
    
    -- order_num이 0이면 자동으로 다음 순서 할당
    IF NEW.order_num = 0 THEN
        SELECT COALESCE(MAX(order_num), 0) + 1
        INTO v_max_order
        FROM public.map_google_place
        WHERE source_type = NEW.source_type
            AND CASE source_type
                WHEN 'youtube_video' THEN youtube_video_id
                WHEN 'instagram_post' THEN instagram_post_id
                WHEN 'blog_post' THEN blog_post_id::TEXT
                WHEN 'text_content' THEN text_content_id::TEXT
            END = v_source_id;
        
        NEW.order_num := v_max_order;
    END IF;
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_mgp_auto_order
    BEFORE INSERT ON public.map_google_place
    FOR EACH ROW
    EXECUTE FUNCTION public.auto_assign_order_num();






-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                               3. 함수 정의                                 ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * FUNCTION: Google Place 데이터 Upsert
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.upsert_google_place_data(
    p_google_place_id VARCHAR(255),
    p_display_name TEXT,
    p_resource_name TEXT DEFAULT NULL,
    p_display_name_lang VARCHAR(10) DEFAULT NULL,
    p_types TEXT[] DEFAULT NULL,
    p_primary_type VARCHAR(127) DEFAULT NULL,
    p_primary_type_display_name TEXT DEFAULT NULL,
    p_formatted_address TEXT DEFAULT NULL,
    p_short_formatted_address TEXT DEFAULT NULL,
    p_latitude NUMERIC(10,7) DEFAULT NULL,
    p_longitude NUMERIC(10,7) DEFAULT NULL,
    p_viewport_low_lat NUMERIC(10,7) DEFAULT NULL,
    p_viewport_low_lng NUMERIC(10,7) DEFAULT NULL,
    p_viewport_high_lat NUMERIC(10,7) DEFAULT NULL,
    p_viewport_high_lng NUMERIC(10,7) DEFAULT NULL,
    p_rating NUMERIC(2,1) DEFAULT NULL,
    p_user_rating_count INTEGER DEFAULT NULL,
    p_business_status VARCHAR(30) DEFAULT NULL,
    p_price_level VARCHAR(30) DEFAULT NULL,
    p_utc_offset_minutes SMALLINT DEFAULT NULL,
    p_timezone_id VARCHAR(63) DEFAULT NULL,
    p_national_phone_number VARCHAR(30) DEFAULT NULL,
    p_international_phone_number VARCHAR(30) DEFAULT NULL,
    p_website_uri TEXT DEFAULT NULL,
    p_google_maps_uri TEXT DEFAULT NULL,
    p_editorial_summary TEXT DEFAULT NULL,
    p_generative_summary TEXT DEFAULT NULL,
    p_review_summary TEXT DEFAULT NULL,
    p_plus_code_global VARCHAR(20) DEFAULT NULL,
    p_plus_code_compound VARCHAR(100) DEFAULT NULL,
    p_opening_hours_periods JSONB DEFAULT NULL,
    p_opening_hours_weekday_descriptions JSONB DEFAULT NULL,
    p_photos JSONB DEFAULT NULL,
    p_reviews JSONB DEFAULT NULL,
    p_address_components JSONB DEFAULT NULL,
    -- 서비스 옵션
    p_takeout BOOLEAN DEFAULT NULL,
    p_delivery BOOLEAN DEFAULT NULL,
    p_dine_in BOOLEAN DEFAULT NULL,
    p_reservable BOOLEAN DEFAULT NULL,
    p_outdoor_seating BOOLEAN DEFAULT NULL,
    -- 음식 서비스
    p_serves_breakfast BOOLEAN DEFAULT NULL,
    p_serves_lunch BOOLEAN DEFAULT NULL,
    p_serves_dinner BOOLEAN DEFAULT NULL,
    p_serves_brunch BOOLEAN DEFAULT NULL,
    p_serves_vegetarian_food BOOLEAN DEFAULT NULL,
    -- 분위기
    p_good_for_children BOOLEAN DEFAULT NULL,
    p_good_for_groups BOOLEAN DEFAULT NULL,
    p_allows_dogs BOOLEAN DEFAULT NULL,
    -- 결제 옵션
    p_accepts_credit_cards BOOLEAN DEFAULT NULL,
    p_accepts_nfc BOOLEAN DEFAULT NULL,
    -- 접근성
    p_wheelchair_accessible_entrance BOOLEAN DEFAULT NULL,
    -- 지역 코드
    p_country_code VARCHAR(2) DEFAULT 'AA',
    p_city_code VARCHAR(96) DEFAULT NULL,
    p_district_code VARCHAR(96) DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    -- 필수 파라미터 체크
    IF p_google_place_id IS NULL OR p_google_place_id = '' THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'google_place_id is required'
        );
    END IF;
    
    IF p_display_name IS NULL OR p_display_name = '' THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'display_name is required'
        );
    END IF;

    -- Upsert
    INSERT INTO public.google_place (
        google_place_id,
        resource_name,
        display_name,
        display_name_lang,
        types,
        primary_type,
        primary_type_display_name,
        formatted_address,
        short_formatted_address,
        latitude,
        longitude,
        viewport_low_lat,
        viewport_low_lng,
        viewport_high_lat,
        viewport_high_lng,
        rating,
        user_rating_count,
        business_status,
        price_level,
        utc_offset_minutes,
        timezone_id,
        national_phone_number,
        international_phone_number,
        website_uri,
        google_maps_uri,
        editorial_summary,
        generative_summary,
        review_summary,
        plus_code_global,
        plus_code_compound,
        opening_hours_periods,
        opening_hours_weekday_descriptions,
        photos,
        reviews,
        address_components,
        takeout,
        delivery,
        dine_in,
        reservable,
        outdoor_seating,
        serves_breakfast,
        serves_lunch,
        serves_dinner,
        serves_brunch,
        serves_vegetarian_food,
        good_for_children,
        good_for_groups,
        allows_dogs,
        accepts_credit_cards,
        accepts_nfc,
        wheelchair_accessible_entrance,
        country_code,
        city_code,
        district_code,
        fetched_at
    ) VALUES (
        p_google_place_id,
        p_resource_name,
        p_display_name,
        p_display_name_lang,
        p_types,
        p_primary_type,
        p_primary_type_display_name,
        p_formatted_address,
        p_short_formatted_address,
        p_latitude,
        p_longitude,
        p_viewport_low_lat,
        p_viewport_low_lng,
        p_viewport_high_lat,
        p_viewport_high_lng,
        p_rating,
        p_user_rating_count,
        p_business_status,
        p_price_level,
        p_utc_offset_minutes,
        p_timezone_id,
        p_national_phone_number,
        p_international_phone_number,
        p_website_uri,
        p_google_maps_uri,
        p_editorial_summary,
        p_generative_summary,
        p_review_summary,
        p_plus_code_global,
        p_plus_code_compound,
        p_opening_hours_periods,
        p_opening_hours_weekday_descriptions,
        p_photos,
        p_reviews,
        p_address_components,
        p_takeout,
        p_delivery,
        p_dine_in,
        p_reservable,
        p_outdoor_seating,
        p_serves_breakfast,
        p_serves_lunch,
        p_serves_dinner,
        p_serves_brunch,
        p_serves_vegetarian_food,
        p_good_for_children,
        p_good_for_groups,
        p_allows_dogs,
        p_accepts_credit_cards,
        p_accepts_nfc,
        p_wheelchair_accessible_entrance,
        p_country_code,
        p_city_code,
        p_district_code,
        NOW()
    )
    ON CONFLICT (google_place_id) DO UPDATE SET
        resource_name = COALESCE(EXCLUDED.resource_name, public.google_place.resource_name),
        display_name = EXCLUDED.display_name,
        display_name_lang = COALESCE(EXCLUDED.display_name_lang, public.google_place.display_name_lang),
        types = COALESCE(EXCLUDED.types, public.google_place.types),
        primary_type = COALESCE(EXCLUDED.primary_type, public.google_place.primary_type),
        primary_type_display_name = COALESCE(EXCLUDED.primary_type_display_name, public.google_place.primary_type_display_name),
        formatted_address = COALESCE(EXCLUDED.formatted_address, public.google_place.formatted_address),
        short_formatted_address = COALESCE(EXCLUDED.short_formatted_address, public.google_place.short_formatted_address),
        latitude = COALESCE(EXCLUDED.latitude, public.google_place.latitude),
        longitude = COALESCE(EXCLUDED.longitude, public.google_place.longitude),
        viewport_low_lat = COALESCE(EXCLUDED.viewport_low_lat, public.google_place.viewport_low_lat),
        viewport_low_lng = COALESCE(EXCLUDED.viewport_low_lng, public.google_place.viewport_low_lng),
        viewport_high_lat = COALESCE(EXCLUDED.viewport_high_lat, public.google_place.viewport_high_lat),
        viewport_high_lng = COALESCE(EXCLUDED.viewport_high_lng, public.google_place.viewport_high_lng),
        rating = COALESCE(EXCLUDED.rating, public.google_place.rating),
        user_rating_count = COALESCE(EXCLUDED.user_rating_count, public.google_place.user_rating_count),
        business_status = COALESCE(EXCLUDED.business_status, public.google_place.business_status),
        price_level = COALESCE(EXCLUDED.price_level, public.google_place.price_level),
        utc_offset_minutes = COALESCE(EXCLUDED.utc_offset_minutes, public.google_place.utc_offset_minutes),
        timezone_id = COALESCE(EXCLUDED.timezone_id, public.google_place.timezone_id),
        national_phone_number = COALESCE(EXCLUDED.national_phone_number, public.google_place.national_phone_number),
        international_phone_number = COALESCE(EXCLUDED.international_phone_number, public.google_place.international_phone_number),
        website_uri = COALESCE(EXCLUDED.website_uri, public.google_place.website_uri),
        google_maps_uri = COALESCE(EXCLUDED.google_maps_uri, public.google_place.google_maps_uri),
        editorial_summary = COALESCE(EXCLUDED.editorial_summary, public.google_place.editorial_summary),
        generative_summary = COALESCE(EXCLUDED.generative_summary, public.google_place.generative_summary),
        review_summary = COALESCE(EXCLUDED.review_summary, public.google_place.review_summary),
        plus_code_global = COALESCE(EXCLUDED.plus_code_global, public.google_place.plus_code_global),
        plus_code_compound = COALESCE(EXCLUDED.plus_code_compound, public.google_place.plus_code_compound),
        opening_hours_periods = COALESCE(EXCLUDED.opening_hours_periods, public.google_place.opening_hours_periods),
        opening_hours_weekday_descriptions = COALESCE(EXCLUDED.opening_hours_weekday_descriptions, public.google_place.opening_hours_weekday_descriptions),
        photos = COALESCE(EXCLUDED.photos, public.google_place.photos),
        reviews = COALESCE(EXCLUDED.reviews, public.google_place.reviews),
        address_components = COALESCE(EXCLUDED.address_components, public.google_place.address_components),
        takeout = COALESCE(EXCLUDED.takeout, public.google_place.takeout),
        delivery = COALESCE(EXCLUDED.delivery, public.google_place.delivery),
        dine_in = COALESCE(EXCLUDED.dine_in, public.google_place.dine_in),
        reservable = COALESCE(EXCLUDED.reservable, public.google_place.reservable),
        outdoor_seating = COALESCE(EXCLUDED.outdoor_seating, public.google_place.outdoor_seating),
        serves_breakfast = COALESCE(EXCLUDED.serves_breakfast, public.google_place.serves_breakfast),
        serves_lunch = COALESCE(EXCLUDED.serves_lunch, public.google_place.serves_lunch),
        serves_dinner = COALESCE(EXCLUDED.serves_dinner, public.google_place.serves_dinner),
        serves_brunch = COALESCE(EXCLUDED.serves_brunch, public.google_place.serves_brunch),
        serves_vegetarian_food = COALESCE(EXCLUDED.serves_vegetarian_food, public.google_place.serves_vegetarian_food),
        good_for_children = COALESCE(EXCLUDED.good_for_children, public.google_place.good_for_children),
        good_for_groups = COALESCE(EXCLUDED.good_for_groups, public.google_place.good_for_groups),
        allows_dogs = COALESCE(EXCLUDED.allows_dogs, public.google_place.allows_dogs),
        accepts_credit_cards = COALESCE(EXCLUDED.accepts_credit_cards, public.google_place.accepts_credit_cards),
        accepts_nfc = COALESCE(EXCLUDED.accepts_nfc, public.google_place.accepts_nfc),
        wheelchair_accessible_entrance = COALESCE(EXCLUDED.wheelchair_accessible_entrance, public.google_place.wheelchair_accessible_entrance),
        country_code = COALESCE(EXCLUDED.country_code, public.google_place.country_code),
        city_code = COALESCE(EXCLUDED.city_code, public.google_place.city_code),
        district_code = COALESCE(EXCLUDED.district_code, public.google_place.district_code),
        fetched_at = NOW()
    RETURNING id INTO v_id;

    RETURN jsonb_build_object(
        'success', true,
        'id', v_id,
        'google_place_id', p_google_place_id
    );
END;
$$;

COMMENT ON FUNCTION public.upsert_google_place_data IS 
'Google Places API 응답을 google_place 테이블에 저장';





/*
 ***********************************************************************************************
 * FUNCTION: AI 추출 Google Place 매핑 저장 (타입별 ID 사용)
 ***********************************************************************************************
 * 설명: 타입에 맞는 전용 ID 컬럼에 값을 저장
 * 용도: AI가 콘텐츠에서 장소를 추출한 후 매핑 저장
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.upsert_google_place_mapping(
    p_google_place_id VARCHAR(255),
    p_source_type VARCHAR(50),
    p_youtube_video_id VARCHAR(20) DEFAULT NULL,
    p_instagram_post_id VARCHAR(50) DEFAULT NULL,
    p_blog_post_id BIGINT DEFAULT NULL,
    p_text_content_id BIGINT DEFAULT NULL,
    p_confidence_score NUMERIC(3,2) DEFAULT NULL,
    p_extraction_method VARCHAR(50) DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_id BIGINT;
    v_source_id TEXT;
BEGIN
    -- google_place_id 존재 확인
    IF NOT EXISTS (
        SELECT 1 FROM public.google_place 
        WHERE google_place_id = p_google_place_id
    ) THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'google_place_id not found'
        );
    END IF;
    
    -- source_type 검증
    IF p_source_type NOT IN ('youtube_video', 'instagram_post', 'blog_post', 'text_content') THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'invalid source_type'
        );
    END IF;
    
    -- source_id 추출 (반환용)
    v_source_id := CASE p_source_type
        WHEN 'youtube_video' THEN p_youtube_video_id
        WHEN 'instagram_post' THEN p_instagram_post_id
        WHEN 'blog_post' THEN p_blog_post_id::TEXT
        WHEN 'text_content' THEN p_text_content_id::TEXT
    END;
    
    -- 해당 타입의 ID가 NULL인지 확인
    IF v_source_id IS NULL THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'source_id for ' || p_source_type || ' is required'
        );
    END IF;

    -- Upsert
    INSERT INTO public.map_google_place (
        google_place_id,
        source_type,
        youtube_video_id,
        instagram_post_id,
        blog_post_id,
        text_content_id,
        confidence_score,
        extraction_method,
        extracted_at
    ) VALUES (
        p_google_place_id,
        p_source_type,
        p_youtube_video_id,
        p_instagram_post_id,
        p_blog_post_id,
        p_text_content_id,
        p_confidence_score,
        p_extraction_method,
        NOW()
    )
    ON CONFLICT (google_place_id, source_type, 
                COALESCE(youtube_video_id, instagram_post_id, 
                        blog_post_id::TEXT, text_content_id::TEXT)) 
    DO UPDATE SET
        confidence_score = COALESCE(EXCLUDED.confidence_score, map_google_place.confidence_score),
        extraction_method = COALESCE(EXCLUDED.extraction_method, map_google_place.extraction_method),
        extracted_at = NOW()
    RETURNING id INTO v_id;
    
    RETURN jsonb_build_object(
        'success', true,
        'id', v_id,
        'google_place_id', p_google_place_id,
        'source_type', p_source_type,
        'source_id', v_source_id
    );
END;
$$;





/*
 ***********************************************************************************************
 * FUNCTION: 특정 콘텐츠의 Google Place 목록 조회
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_google_places_for_content(
    p_source_type VARCHAR(50),
    p_source_id TEXT
)
RETURNS TABLE (
    google_place_id VARCHAR(255),
    display_name TEXT,
    name_ko TEXT,
    primary_type VARCHAR(127),
    formatted_address TEXT,
    rating NUMERIC(2,1),
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    confidence_score NUMERIC(3,2),
    is_verified BOOLEAN
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        gp.google_place_id,
        gp.display_name,
        gp.name_ko,
        gp.primary_type,
        gp.formatted_address,
        gp.rating,
        gp.latitude,
        gp.longitude,
        mgp.confidence_score,
        mgp.is_verified
    FROM public.map_google_place mgp
    JOIN public.google_place gp 
        ON mgp.google_place_id = gp.google_place_id
    WHERE mgp.source_type = p_source_type
        AND (
            (p_source_type = 'youtube_video'  AND mgp.youtube_video_id      = p_source_id)
            OR (p_source_type = 'instagram_post' AND mgp.instagram_post_id     = p_source_id)
            OR (p_source_type = 'blog_post'      AND mgp.blog_post_id::TEXT    = p_source_id)
            OR (p_source_type = 'text_content'   AND mgp.text_content_id::TEXT = p_source_id)
        )
    ORDER BY mgp.confidence_score DESC NULLS LAST, mgp.order_num;
$$;



/*
 ***********************************************************************************************
 * FUNCTION: 특정 Google Place의 콘텐츠 목록 조회
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_content_for_google_place(
    p_google_place_id VARCHAR(255),
    p_source_type VARCHAR(50) DEFAULT NULL,
    p_verified_only BOOLEAN DEFAULT FALSE
)
RETURNS TABLE (
    source_type VARCHAR(50),
    youtube_video_id VARCHAR(20),
    instagram_post_id VARCHAR(50),
    blog_post_id BIGINT,
    text_content_id BIGINT,
    confidence_score NUMERIC(3,2),
    is_verified BOOLEAN,
    is_selected BOOLEAN,
    order_num INTEGER,
    created_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        mgp.source_type,
        mgp.youtube_video_id,
        mgp.instagram_post_id,
        mgp.blog_post_id,
        mgp.text_content_id,
        mgp.confidence_score,
        mgp.is_verified,
        mgp.is_selected,
        mgp.order_num,
        mgp.created_at
    FROM public.map_google_place mgp
    WHERE mgp.google_place_id = p_google_place_id
        AND (p_source_type IS NULL OR mgp.source_type = p_source_type)
        AND (NOT p_verified_only OR mgp.is_verified = TRUE)
    ORDER BY mgp.order_num, mgp.created_at DESC;
$$;



/*
 ***********************************************************************************************
 * FUNCTION: 지역별 Google Place 조회
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_google_places_by_location(
    p_city_code VARCHAR(96) DEFAULT NULL,
    p_district_code VARCHAR(96) DEFAULT NULL,
    p_primary_type VARCHAR(127) DEFAULT NULL,
    p_min_rating NUMERIC(2,1) DEFAULT NULL,
    p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
    id BIGINT,
    google_place_id VARCHAR(255),
    display_name TEXT,
    name_ko TEXT,
    primary_type VARCHAR(127),
    formatted_address TEXT,
    rating NUMERIC(2,1),
    user_rating_count INTEGER,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    business_status VARCHAR(30),
    price_level VARCHAR(30)
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        gp.id,
        gp.google_place_id,
        gp.display_name,
        gp.name_ko,
        gp.primary_type,
        gp.formatted_address,
        gp.rating,
        gp.user_rating_count,
        gp.latitude,
        gp.longitude,
        gp.business_status,
        gp.price_level
    FROM public.google_place gp
    WHERE (p_city_code IS NULL OR gp.city_code = p_city_code)
        AND (p_district_code IS NULL OR gp.district_code = p_district_code)
        AND (p_primary_type IS NULL OR gp.primary_type = p_primary_type)
        AND (p_min_rating IS NULL OR gp.rating >= p_min_rating)
        AND gp.is_active = TRUE
        AND gp.is_display = TRUE
    ORDER BY gp.rating DESC NULLS LAST, gp.user_rating_count DESC NULLS LAST
    LIMIT p_limit;
$$;


/*
 ***********************************************************************************************
 * FUNCTION: 매핑 검증 (타입별 ID 사용)
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.verify_google_place_mapping(
    p_google_place_id VARCHAR(255),
    p_source_type VARCHAR(50),
    p_youtube_video_id VARCHAR(20) DEFAULT NULL,
    p_instagram_post_id VARCHAR(50) DEFAULT NULL,
    p_blog_post_id BIGINT DEFAULT NULL,
    p_text_content_id BIGINT DEFAULT NULL,
    p_verified_by VARCHAR(255) DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_rows_affected INTEGER;
BEGIN
    UPDATE public.map_google_place
    SET is_verified = TRUE,
        verified_at = NOW(),
        verified_by = p_verified_by
    WHERE google_place_id = p_google_place_id
        AND source_type = p_source_type
        AND (
            (p_source_type = 'youtube_video' AND youtube_video_id = p_youtube_video_id)
            OR (p_source_type = 'instagram_post' AND instagram_post_id = p_instagram_post_id)
            OR (p_source_type = 'blog_post' AND blog_post_id = p_blog_post_id)
            OR (p_source_type = 'text_content' AND text_content_id = p_text_content_id)
        );
    
    GET DIAGNOSTICS v_rows_affected = ROW_COUNT;
    
    IF v_rows_affected = 0 THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'mapping not found'
        );
    END IF;
    
    RETURN jsonb_build_object(
        'success', true,
        'verified', true,
        'verified_at', NOW()
    );
END;
$$;

COMMENT ON FUNCTION public.verify_google_place_mapping IS 
'장소 매핑 검증 (타입별 전용 ID 사용)';


/*
 ***********************************************************************************************
 * FUNCTION: 선택된 장소 설정 (타입별 ID 사용)
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.set_selected_places(
    p_source_type VARCHAR(50),
    p_youtube_video_id VARCHAR(20) DEFAULT NULL,
    p_instagram_post_id VARCHAR(50) DEFAULT NULL,
    p_blog_post_id BIGINT DEFAULT NULL,
    p_text_content_id BIGINT DEFAULT NULL,
    p_google_place_ids VARCHAR(255)[] DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_updated_count INTEGER;
BEGIN
    -- 모든 장소의 선택 해제
    UPDATE public.map_google_place
    SET is_selected = FALSE
    WHERE source_type = p_source_type
        AND (
            (p_source_type = 'youtube_video' AND youtube_video_id = p_youtube_video_id)
            OR (p_source_type = 'instagram_post' AND instagram_post_id = p_instagram_post_id)
            OR (p_source_type = 'blog_post' AND blog_post_id = p_blog_post_id)
            OR (p_source_type = 'text_content' AND text_content_id = p_text_content_id)
        );
    
    -- 지정된 장소만 선택 (NULL이 아닌 경우)
    IF p_google_place_ids IS NOT NULL AND array_length(p_google_place_ids, 1) > 0 THEN
        UPDATE public.map_google_place
        SET is_selected = TRUE
        WHERE source_type = p_source_type
            AND (
                (p_source_type = 'youtube_video' AND youtube_video_id = p_youtube_video_id)
                OR (p_source_type = 'instagram_post' AND instagram_post_id = p_instagram_post_id)
                OR (p_source_type = 'blog_post' AND blog_post_id = p_blog_post_id)
                OR (p_source_type = 'text_content' AND text_content_id = p_text_content_id)
            )
            AND google_place_id = ANY(p_google_place_ids);
        
        GET DIAGNOSTICS v_updated_count = ROW_COUNT;
    ELSE
        v_updated_count := 0;
    END IF;
    
    RETURN jsonb_build_object(
        'success', true,
        'selected_count', v_updated_count
    );
END;
$$;

COMMENT ON FUNCTION public.set_selected_places IS 
'콘텐츠의 선택된 장소 설정 (타입별 전용 ID 사용)';


/*
 ***********************************************************************************************
 * FUNCTION: 주변 장소 검색 (PostGIS 활용)
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_nearby_google_places(
    p_latitude NUMERIC(10,7),
    p_longitude NUMERIC(10,7),
    p_radius_meters INTEGER DEFAULT 1000,
    p_primary_type VARCHAR(127) DEFAULT NULL,
    p_min_rating NUMERIC(2,1) DEFAULT NULL,
    p_limit INTEGER DEFAULT 20
)
RETURNS TABLE (
    google_place_id VARCHAR(255),
    display_name TEXT,
    name_ko TEXT,
    primary_type VARCHAR(127),
    formatted_address TEXT,
    rating NUMERIC(2,1),
    user_rating_count INTEGER,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    distance_meters NUMERIC,
    google_maps_uri TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        gp.google_place_id,
        gp.display_name,
        gp.name_ko,
        gp.primary_type,
        gp.formatted_address,
        gp.rating,
        gp.user_rating_count,
        gp.latitude,
        gp.longitude,
        ST_Distance(
            gp.location_point,
            ST_GeogFromText('POINT(' || p_longitude || ' ' || p_latitude || ')')
        )::NUMERIC AS distance_meters,
        gp.google_maps_uri
    FROM public.google_place gp
    WHERE gp.location_point IS NOT NULL
        AND ST_DWithin(
            gp.location_point,
            ST_GeogFromText('POINT(' || p_longitude || ' ' || p_latitude || ')'),
            p_radius_meters
        )
        AND (p_primary_type IS NULL OR gp.primary_type = p_primary_type)
        AND (p_min_rating IS NULL OR gp.rating >= p_min_rating)
        AND gp.is_active = TRUE
        AND gp.is_display = TRUE
    ORDER BY distance_meters ASC
    LIMIT p_limit;
$$;

COMMENT ON FUNCTION public.get_nearby_google_places IS 
'주변 장소 검색 (PostGIS ST_DWithin 사용)';


/*
 ***********************************************************************************************
 * FUNCTION: 장소별 매핑 통계
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_place_mapping_stats(
    p_google_place_id VARCHAR(255)
)
RETURNS TABLE (
    total_mappings BIGINT,
    verified_mappings BIGINT,
    avg_confidence NUMERIC,
    youtube_count BIGINT,
    instagram_count BIGINT,
    blog_count BIGINT,
    text_count BIGINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        COUNT(*)::BIGINT AS total_mappings,
        COUNT(*) FILTER (WHERE is_verified = TRUE)::BIGINT AS verified_mappings,
        AVG(confidence_score) AS avg_confidence,
        COUNT(*) FILTER (WHERE source_type = 'youtube_video')::BIGINT AS youtube_count,
        COUNT(*) FILTER (WHERE source_type = 'instagram_post')::BIGINT AS instagram_count,
        COUNT(*) FILTER (WHERE source_type = 'blog_post')::BIGINT AS blog_count,
        COUNT(*) FILTER (WHERE source_type = 'text_content')::BIGINT AS text_count
    FROM public.map_google_place
    WHERE google_place_id = p_google_place_id;
$$;