/*
 * aiqna db for web service (Custom Content and Mapping Tables)
 * Database Name 'aiqna'
 *
 * Created 2024-10-12
 * Updated 2025-12-01
 * 
 * 용도: Google Places API에서 가져올 수 없는 콘텐츠 관리
 *   - 전시회, 팝업스토어, 축제, 콘서트, 마켓 등 일시적 이벤트
 *   - 투어 코스, 여행 테마, 추천 루트 등 큐레이션 콘텐츠
 * 
 * 테이블:
 *   1. custom_content         - 커스텀 콘텐츠 (이벤트/큐레이션)
 *   2. custom_content_i18n    - 다국어 지원
 *   3. map_custom_content     - 소스 콘텐츠 매핑
 * 
 * 함수:
 *   - upsert_custom_content()           - 콘텐츠 저장
 *   - upsert_custom_content_mapping()   - 매핑 저장
 *   - get_custom_contents_for_source()  - 소스별 콘텐츠 조회
 *   - get_sources_for_custom_content()  - 콘텐츠별 소스 조회
 *   - get_custom_contents_by_filter()   - 필터링 조회
 */


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                        1. CUSTOM_CONTENT 테이블                            ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: custom_content
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.custom_content (
    -- ========================================
    -- 기본 키
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_code VARCHAR(100) NOT NULL,             -- 고유 코드 (예: EVT-2024-PICASSO-EXHIBITION)
    
    -- ========================================
    -- 콘텐츠 유형
    -- ========================================
    content_type VARCHAR(30) NOT NULL,              -- event, tour, collection
    content_subtype VARCHAR(50) NULL,               -- exhibition, popup, festival, concert, market, fair, tour_course, theme, route, collection
    
    -- ========================================
    -- 지역 연결 (FK)
    -- ========================================
    country_code VARCHAR(2) NOT NULL DEFAULT 'AA',
    city_code VARCHAR(96) NULL,
    district_code VARCHAR(96) NULL,
    
    -- ========================================
    -- 기본 정보 (다국어)
    -- ========================================
    name TEXT NOT NULL,                             -- 기본 이름 (원어)
    name_en TEXT NULL,                              -- 영문 이름
    name_ko TEXT NULL,                              -- 한국어 이름
    
    subtitle TEXT NULL,                             -- 부제목/슬로건
    
    description TEXT NULL,                          -- 상세 설명 (원어)
    description_en TEXT NULL,                       -- 영문 설명
    description_ko TEXT NULL,                       -- 한국어 설명
    
    -- ========================================
    -- 운영 기간
    -- ========================================
    is_permanent BOOLEAN NOT NULL DEFAULT FALSE,    -- 상설 여부
    period_start DATE NULL,                         -- 시작일
    period_end DATE NULL,                           -- 종료일
    period_note TEXT NULL,                          -- 기간 관련 메모
    
    -- ========================================
    -- 운영 시간
    -- ========================================
    opening_hours_text TEXT NULL,                   -- 운영 시간 텍스트
    opening_hours_json JSONB NULL,                  -- 구조화된 운영 시간
    last_entry_minutes_before SMALLINT NULL,        -- 마감 N분 전 입장 마감
    
    -- ========================================
    -- 장소 정보 (행사 장소)
    -- ========================================
    venue_name TEXT NULL,                           -- 행사 장소명
    venue_name_en TEXT NULL,
    venue_google_place_id VARCHAR(255) NULL,        -- Google Place 연결
    
    -- 주소
    address TEXT NULL,                              -- 전체 주소
    address_detail TEXT NULL,                       -- 상세 주소
    
    -- 위치 좌표
    latitude NUMERIC(10,7) NULL,
    longitude NUMERIC(10,7) NULL,
    
    -- 자동 생성 지리 객체
    location_point GEOGRAPHY(POINT, 4326)
        GENERATED ALWAYS AS (
            CASE 
                WHEN latitude IS NOT NULL AND longitude IS NOT NULL 
                THEN geography(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326))
                ELSE NULL
            END
        ) STORED,
    
    -- 복수 지점 (투어, 컬렉션용)
    spot_count INTEGER NULL,                        -- 포함된 장소 수
    spots_json JSONB NULL,                          -- 장소 목록 [{name, lat, lng, google_place_id, order}]
    
    -- ========================================
    -- 연락처
    -- ========================================
    phone VARCHAR(30) NULL,
    email VARCHAR(255) NULL,
    website_url TEXT NULL,
    
    -- ========================================
    -- 가격 정보
    -- ========================================
    is_free BOOLEAN NOT NULL DEFAULT FALSE,         -- 무료 여부
    price_info TEXT NULL,                           -- 가격 텍스트
    price_adult NUMERIC(12,2) NULL,                 -- 성인 가격
    price_youth NUMERIC(12,2) NULL,                 -- 청소년 가격
    price_child NUMERIC(12,2) NULL,                 -- 어린이 가격
    price_currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
    
    discount_info TEXT NULL,                        -- 할인 정보
    
    -- ========================================
    -- 예약/티켓
    -- ========================================
    is_reservation_required BOOLEAN NULL,
    reservation_url TEXT NULL,
    ticket_url TEXT NULL,
    ticket_platform VARCHAR(100) NULL,
    
    -- ========================================
    -- 소요 시간
    -- ========================================
    duration_minutes_min SMALLINT NULL,
    duration_minutes_max SMALLINT NULL,
    
    -- ========================================
    -- 타겟 그룹
    -- ========================================
    is_target_for_family BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_children BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_couple BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_friends BOOLEAN NOT NULL DEFAULT FALSE,
    is_target_for_solo BOOLEAN NOT NULL DEFAULT FALSE,
    
    age_restriction VARCHAR(30) NULL,               -- 연령 제한
    
    -- ========================================
    -- 분류 태그
    -- ========================================
    categories TEXT[] NULL,                         -- 카테고리
    tags TEXT[] NULL,                               -- 태그
    
    -- ========================================
    -- 이미지
    -- ========================================
    thumbnail_url TEXT NULL,                        -- 대표 이미지
    poster_url TEXT NULL,                           -- 포스터 이미지
    images JSONB NULL,                              -- 이미지 목록
    
    -- ========================================
    -- 주최/주관
    -- ========================================
    organizer TEXT NULL,
    organizer_en TEXT NULL,
    sponsor TEXT NULL,
    
    -- ========================================
    -- 외부 링크
    -- ========================================
    naver_map_url TEXT NULL,
    kakao_map_url TEXT NULL,
    instagram_url TEXT NULL,
    instagram_hashtag VARCHAR(100) NULL,
    youtube_url TEXT NULL,
    blog_url TEXT NULL,
    
    -- ========================================
    -- 접근성
    -- ========================================
    is_wheelchair_accessible BOOLEAN NULL,
    is_parking_available BOOLEAN NULL,
    parking_info TEXT NULL,
    public_transport_info TEXT NULL,
    
    -- ========================================
    -- 기타 안내
    -- ========================================
    amenities TEXT[] NULL,
    restrictions TEXT[] NULL,
    tips TEXT[] NULL,
    
    -- ========================================
    -- 인기도/추천
    -- ========================================
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count INTEGER NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    featured_order INTEGER NULL,
    
    -- ========================================
    -- 관리자 정보
    -- ========================================
    created_by VARCHAR(255) NULL,
    approved_by VARCHAR(255) NULL,
    approved_at TIMESTAMPTZ NULL,
    
    -- ========================================
    -- 시스템 관리
    -- ========================================
    metadata_json JSONB NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_display BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    
    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ NULL,

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT cc_content_code_unique 
        UNIQUE (content_code),
    
    -- FK
    CONSTRAINT cc_country_code_fkey
        FOREIGN KEY (country_code)
        REFERENCES public.countries (country_code)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT cc_city_code_fkey
        FOREIGN KEY (city_code)
        REFERENCES public.cities (city_code)
        ON UPDATE CASCADE ON DELETE SET NULL,
    
    CONSTRAINT cc_district_code_fkey
        FOREIGN KEY (district_code)
        REFERENCES public.districts (district_code)
        ON UPDATE CASCADE ON DELETE SET NULL,
    
    CONSTRAINT cc_venue_google_place_fkey
        FOREIGN KEY (venue_google_place_id)
        REFERENCES public.google_place (google_place_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    
    -- 값 검증
    CONSTRAINT cc_content_type_check 
        CHECK (content_type IN ('event', 'tour', 'collection')),
    
    CONSTRAINT cc_content_subtype_check 
        CHECK (content_subtype IS NULL OR content_subtype IN (
            -- event subtypes
            'exhibition', 'popup', 'festival', 'concert', 'market', 'fair', 'performance', 'workshop', 'seminar',
            -- tour subtypes
            'tour_course', 'theme', 'route', 'day_trip',
            -- collection subtypes
            'collection', 'ranking', 'recommendation'
        )),
    
    CONSTRAINT cc_latitude_check 
        CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
    
    CONSTRAINT cc_longitude_check 
        CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
    
    CONSTRAINT cc_period_check 
        CHECK (
            is_permanent = TRUE
            OR
            (period_start IS NOT NULL AND period_end IS NOT NULL AND period_start <= period_end)
            OR
            (period_start IS NOT NULL AND period_end IS NULL)
        ),
    
    CONSTRAINT cc_duration_check 
        CHECK (
            (duration_minutes_min IS NULL AND duration_minutes_max IS NULL)
            OR
            (duration_minutes_min IS NOT NULL AND duration_minutes_max IS NOT NULL 
            AND duration_minutes_min > 0 AND duration_minutes_max > 0
            AND duration_minutes_min <= duration_minutes_max)
        ),
    
    CONSTRAINT cc_price_check
        CHECK (price_adult IS NULL OR price_adult >= 0),
    
    CONSTRAINT cc_spot_count_check
        CHECK (spot_count IS NULL OR spot_count >= 0),
    
    CONSTRAINT cc_view_count_check
        CHECK (view_count >= 0),
    
    CONSTRAINT cc_like_count_check
        CHECK (like_count >= 0),
    
    CONSTRAINT cc_deleted_logic_check
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) 
            OR (is_deleted = TRUE AND deleted_at IS NOT NULL)
        )
);

-- ========================================
-- 인덱스: custom_content
-- ========================================
CREATE INDEX IF NOT EXISTS idx_cc_content_code 
    ON public.custom_content (content_code);

CREATE INDEX IF NOT EXISTS idx_cc_content_type 
    ON public.custom_content (content_type);

CREATE INDEX IF NOT EXISTS idx_cc_content_subtype 
    ON public.custom_content (content_subtype) 
    WHERE content_subtype IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_country_code 
    ON public.custom_content (country_code);

CREATE INDEX IF NOT EXISTS idx_cc_city_code 
    ON public.custom_content (city_code) 
    WHERE city_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_district_code 
    ON public.custom_content (district_code) 
    WHERE district_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_period 
    ON public.custom_content (period_start, period_end) 
    WHERE is_permanent = FALSE;

CREATE INDEX IF NOT EXISTS idx_cc_period_end 
    ON public.custom_content (period_end) 
    WHERE period_end IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_name_trgm 
    ON public.custom_content USING GIN (name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_cc_name_ko_trgm 
    ON public.custom_content USING GIN (name_ko gin_trgm_ops) 
    WHERE name_ko IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_location_gist 
    ON public.custom_content USING GIST (location_point) 
    WHERE location_point IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_categories_gin 
    ON public.custom_content USING GIN (categories);

CREATE INDEX IF NOT EXISTS idx_cc_tags_gin 
    ON public.custom_content USING GIN (tags);

CREATE INDEX IF NOT EXISTS idx_cc_is_active 
    ON public.custom_content (is_active, is_display) 
    WHERE is_active = TRUE AND is_display = TRUE;

CREATE INDEX IF NOT EXISTS idx_cc_featured 
    ON public.custom_content (featured_order) 
    WHERE is_featured = TRUE;

CREATE INDEX IF NOT EXISTS idx_cc_is_free 
    ON public.custom_content (is_free) 
    WHERE is_free = TRUE;

CREATE INDEX IF NOT EXISTS idx_cc_target_family 
    ON public.custom_content (is_target_for_family) 
    WHERE is_target_for_family = TRUE;

CREATE INDEX IF NOT EXISTS idx_cc_target_couple 
    ON public.custom_content (is_target_for_couple) 
    WHERE is_target_for_couple = TRUE;

CREATE INDEX IF NOT EXISTS idx_cc_view_count 
    ON public.custom_content (view_count DESC);

CREATE INDEX IF NOT EXISTS idx_cc_like_count 
    ON public.custom_content (like_count DESC);

CREATE INDEX IF NOT EXISTS idx_cc_created_at 
    ON public.custom_content (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cc_published_at 
    ON public.custom_content (published_at DESC) 
    WHERE published_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_images_gin 
    ON public.custom_content USING GIN (images) 
    WHERE images IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cc_spots_gin 
    ON public.custom_content USING GIN (spots_json) 
    WHERE spots_json IS NOT NULL;

-- ========================================
-- RLS: custom_content
-- ========================================
ALTER TABLE public.custom_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "custom_content is visible to everyone"
    ON public.custom_content FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage custom_content"
    ON public.custom_content FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: custom_content updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION public.update_custom_content_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_cc_updated_at
    BEFORE UPDATE ON public.custom_content
    FOR EACH ROW
    EXECUTE FUNCTION public.update_custom_content_updated_at();


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                      2. CUSTOM_CONTENT_I18N 테이블                         ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: custom_content_i18n
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.custom_content_i18n (
    -- ========================================
    -- 기본 키
    -- ========================================
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    content_code VARCHAR(100) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,                 -- ko, en, ja, zh-CN, zh-TW 등
    
    -- ========================================
    -- 번역 필드
    -- ========================================
    name TEXT NOT NULL,
    subtitle TEXT NULL,
    description TEXT NULL,
    venue_name TEXT NULL,
    price_info TEXT NULL,
    opening_hours_text TEXT NULL,
    
    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT cci_content_lang_unique 
        UNIQUE (content_code, lang_code),
    
    CONSTRAINT cci_content_code_fkey
        FOREIGN KEY (content_code) 
        REFERENCES public.custom_content (content_code)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT cci_lang_code_fkey
        FOREIGN KEY (lang_code) 
        REFERENCES public.languages (lang_code)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ========================================
-- 인덱스: custom_content_i18n
-- ========================================
CREATE INDEX IF NOT EXISTS idx_cci_content_code 
    ON public.custom_content_i18n (content_code);

CREATE INDEX IF NOT EXISTS idx_cci_lang_code 
    ON public.custom_content_i18n (lang_code);

CREATE INDEX IF NOT EXISTS idx_cci_name_trgm 
    ON public.custom_content_i18n USING GIN (name gin_trgm_ops);

-- ========================================
-- RLS: custom_content_i18n
-- ========================================
ALTER TABLE public.custom_content_i18n ENABLE ROW LEVEL SECURITY;

CREATE POLICY "custom_content_i18n is visible to everyone"
    ON public.custom_content_i18n FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage custom_content_i18n"
    ON public.custom_content_i18n FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: custom_content_i18n updated_at
-- ========================================
CREATE OR REPLACE FUNCTION public.update_custom_content_i18n_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_cci_updated_at
    BEFORE UPDATE ON public.custom_content_i18n
    FOR EACH ROW
    EXECUTE FUNCTION public.update_custom_content_i18n_updated_at();




-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                      3. MAP_CUSTOM_CONTENT 테이블                          ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: map_custom_content
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.map_custom_content (
    -- ========================================
    -- 기본 키
    -- ========================================
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    
    -- ========================================
    -- 매핑 정보
    -- ========================================
    content_code VARCHAR(100) NOT NULL,
    source_type VARCHAR(50) NOT NULL,               -- youtube_video, instagram_post, blog_post, text_content
    source_id TEXT NOT NULL,
    
    -- ========================================
    -- AI 추출 정보
    -- ========================================
    confidence_score NUMERIC(3,2) NULL,             -- 0.00 ~ 1.00
    extraction_method VARCHAR(50) NULL,             -- ai_analysis, manual, hybrid
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- ========================================
    -- 검증 정보
    -- ========================================
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMPTZ NULL,
    verified_by VARCHAR(255) NULL,
    
    -- ========================================
    -- 표시 순서
    -- ========================================
    is_selected BOOLEAN NOT NULL DEFAULT FALSE,
    order_num INTEGER NOT NULL DEFAULT 0,
    
    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT mcc_mapping_unique 
        UNIQUE (content_code, source_type, source_id),
    
    CONSTRAINT mcc_content_code_fkey
        FOREIGN KEY (content_code) 
        REFERENCES public.custom_content (content_code)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT mcc_source_type_check 
        CHECK (source_type IN ('youtube_video', 'instagram_post', 'blog_post', 'text_content')),
    
    CONSTRAINT mcc_order_num_check 
        CHECK (order_num >= 0),
    
    CONSTRAINT mcc_confidence_check 
        CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1))
);

-- ========================================
-- 인덱스: map_custom_content
-- ========================================
CREATE INDEX IF NOT EXISTS idx_mcc_content_order 
    ON public.map_custom_content (content_code, order_num);

CREATE INDEX IF NOT EXISTS idx_mcc_content_added 
    ON public.map_custom_content (content_code, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mcc_selected 
    ON public.map_custom_content (content_code, order_num) 
    WHERE is_selected = TRUE;

CREATE INDEX IF NOT EXISTS idx_mcc_verified 
    ON public.map_custom_content (content_code, confidence_score DESC) 
    WHERE is_verified = TRUE;

CREATE INDEX IF NOT EXISTS idx_mcc_source 
    ON public.map_custom_content (source_type, source_id);

CREATE INDEX IF NOT EXISTS idx_mcc_high_confidence 
    ON public.map_custom_content (confidence_score DESC) 
    WHERE confidence_score >= 0.8;

-- ========================================
-- RLS: map_custom_content
-- ========================================
ALTER TABLE public.map_custom_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "map_custom_content is visible to everyone"
    ON public.map_custom_content FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage map_custom_content"
    ON public.map_custom_content FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: map_custom_content updated_at
-- ========================================
CREATE OR REPLACE FUNCTION public.update_map_custom_content_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_mcc_updated_at
    BEFORE UPDATE ON public.map_custom_content
    FOR EACH ROW
    EXECUTE FUNCTION public.update_map_custom_content_updated_at();


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                               4. 함수 정의                                 ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * FUNCTION: 커스텀 콘텐츠 Upsert
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.upsert_custom_content(
    p_content_code VARCHAR(100),
    p_content_type VARCHAR(30),
    p_name TEXT,
    p_content_subtype VARCHAR(50) DEFAULT NULL,
    p_name_en TEXT DEFAULT NULL,
    p_name_ko TEXT DEFAULT NULL,
    p_subtitle TEXT DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_is_permanent BOOLEAN DEFAULT FALSE,
    p_period_start DATE DEFAULT NULL,
    p_period_end DATE DEFAULT NULL,
    p_venue_name TEXT DEFAULT NULL,
    p_venue_google_place_id VARCHAR(255) DEFAULT NULL,
    p_address TEXT DEFAULT NULL,
    p_latitude NUMERIC(10,7) DEFAULT NULL,
    p_longitude NUMERIC(10,7) DEFAULT NULL,
    p_is_free BOOLEAN DEFAULT FALSE,
    p_price_info TEXT DEFAULT NULL,
    p_price_adult NUMERIC(12,2) DEFAULT NULL,
    p_is_reservation_required BOOLEAN DEFAULT NULL,
    p_reservation_url TEXT DEFAULT NULL,
    p_categories TEXT[] DEFAULT NULL,
    p_tags TEXT[] DEFAULT NULL,
    p_thumbnail_url TEXT DEFAULT NULL,
    p_country_code VARCHAR(2) DEFAULT 'AA',
    p_city_code VARCHAR(96) DEFAULT NULL,
    p_district_code VARCHAR(96) DEFAULT NULL,
    p_created_by VARCHAR(255) DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    -- 필수 파라미터 체크
    IF p_content_code IS NULL OR p_content_code = '' THEN
        RETURN jsonb_build_object('success', false, 'error', 'content_code is required');
    END IF;
    
    IF p_name IS NULL OR p_name = '' THEN
        RETURN jsonb_build_object('success', false, 'error', 'name is required');
    END IF;

    INSERT INTO public.custom_content (
        content_code, content_type, content_subtype,
        name, name_en, name_ko, subtitle, description,
        is_permanent, period_start, period_end,
        venue_name, venue_google_place_id, address,
        latitude, longitude,
        is_free, price_info, price_adult,
        is_reservation_required, reservation_url,
        categories, tags, thumbnail_url,
        country_code, city_code, district_code,
        created_by
    ) VALUES (
        p_content_code, p_content_type, p_content_subtype,
        p_name, p_name_en, p_name_ko, p_subtitle, p_description,
        p_is_permanent, p_period_start, p_period_end,
        p_venue_name, p_venue_google_place_id, p_address,
        p_latitude, p_longitude,
        p_is_free, p_price_info, p_price_adult,
        p_is_reservation_required, p_reservation_url,
        p_categories, p_tags, p_thumbnail_url,
        p_country_code, p_city_code, p_district_code,
        p_created_by
    )
    ON CONFLICT (content_code) DO UPDATE SET
        content_type = EXCLUDED.content_type,
        content_subtype = COALESCE(EXCLUDED.content_subtype, public.custom_content.content_subtype),
        name = EXCLUDED.name,
        name_en = COALESCE(EXCLUDED.name_en, public.custom_content.name_en),
        name_ko = COALESCE(EXCLUDED.name_ko, public.custom_content.name_ko),
        subtitle = COALESCE(EXCLUDED.subtitle, public.custom_content.subtitle),
        description = COALESCE(EXCLUDED.description, public.custom_content.description),
        is_permanent = EXCLUDED.is_permanent,
        period_start = COALESCE(EXCLUDED.period_start, public.custom_content.period_start),
        period_end = COALESCE(EXCLUDED.period_end, public.custom_content.period_end),
        venue_name = COALESCE(EXCLUDED.venue_name, public.custom_content.venue_name),
        venue_google_place_id = COALESCE(EXCLUDED.venue_google_place_id, public.custom_content.venue_google_place_id),
        address = COALESCE(EXCLUDED.address, public.custom_content.address),
        latitude = COALESCE(EXCLUDED.latitude, public.custom_content.latitude),
        longitude = COALESCE(EXCLUDED.longitude, public.custom_content.longitude),
        is_free = EXCLUDED.is_free,
        price_info = COALESCE(EXCLUDED.price_info, public.custom_content.price_info),
        price_adult = COALESCE(EXCLUDED.price_adult, public.custom_content.price_adult),
        is_reservation_required = COALESCE(EXCLUDED.is_reservation_required, public.custom_content.is_reservation_required),
        reservation_url = COALESCE(EXCLUDED.reservation_url, public.custom_content.reservation_url),
        categories = COALESCE(EXCLUDED.categories, public.custom_content.categories),
        tags = COALESCE(EXCLUDED.tags, public.custom_content.tags),
        thumbnail_url = COALESCE(EXCLUDED.thumbnail_url, public.custom_content.thumbnail_url),
        country_code = COALESCE(EXCLUDED.country_code, public.custom_content.country_code),
        city_code = COALESCE(EXCLUDED.city_code, public.custom_content.city_code),
        district_code = COALESCE(EXCLUDED.district_code, public.custom_content.district_code)
    RETURNING id INTO v_id;

    RETURN jsonb_build_object(
        'success', true,
        'id', v_id,
        'content_code', p_content_code
    );
END;
$$;

COMMENT ON FUNCTION public.upsert_custom_content IS 
'커스텀 콘텐츠를 custom_content 테이블에 저장';


/*
 ***********************************************************************************************
 * FUNCTION: 매핑 저장
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.upsert_custom_content_mapping(
    p_content_code VARCHAR(100),
    p_source_type VARCHAR(50),
    p_source_id TEXT,
    p_confidence_score NUMERIC(3,2) DEFAULT NULL,
    p_extraction_method VARCHAR(50) DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.custom_content 
        WHERE content_code = p_content_code
    ) THEN
        RETURN jsonb_build_object('success', false, 'error', 'content_code not found');
    END IF;

    INSERT INTO public.map_custom_content (
        content_code, source_type, source_id,
        confidence_score, extraction_method, extracted_at
    ) VALUES (
        p_content_code, p_source_type, p_source_id,
        p_confidence_score, p_extraction_method, NOW()
    )
    ON CONFLICT (content_code, source_type, source_id) DO UPDATE SET
        confidence_score = COALESCE(EXCLUDED.confidence_score, public.map_custom_content.confidence_score),
        extraction_method = COALESCE(EXCLUDED.extraction_method, public.map_custom_content.extraction_method),
        extracted_at = NOW()
    RETURNING id INTO v_id;

    RETURN jsonb_build_object(
        'success', true,
        'id', v_id,
        'content_code', p_content_code,
        'source_type', p_source_type,
        'source_id', p_source_id
    );
END;
$$;

COMMENT ON FUNCTION public.upsert_custom_content_mapping IS 
'커스텀 콘텐츠와 소스 매핑 저장';


/*
 ***********************************************************************************************
 * FUNCTION: 소스별 콘텐츠 조회
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_custom_contents_for_source(
    p_source_type VARCHAR(50),
    p_source_id TEXT
)
RETURNS TABLE (
    content_code VARCHAR(100),
    content_type VARCHAR(30),
    name TEXT,
    name_ko TEXT,
    venue_name TEXT,
    period_start DATE,
    period_end DATE,
    confidence_score NUMERIC(3,2),
    is_verified BOOLEAN
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        cc.content_code,
        cc.content_type,
        cc.name,
        cc.name_ko,
        cc.venue_name,
        cc.period_start,
        cc.period_end,
        mcc.confidence_score,
        mcc.is_verified
    FROM public.map_custom_content mcc
    JOIN public.custom_content cc 
      ON mcc.content_code = cc.content_code
    WHERE mcc.source_type = p_source_type
      AND mcc.source_id = p_source_id
      AND cc.is_active = TRUE
    ORDER BY mcc.confidence_score DESC NULLS LAST, mcc.order_num;
$$;


/*
 ***********************************************************************************************
 * FUNCTION: 콘텐츠별 소스 조회
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_sources_for_custom_content(
    p_content_code VARCHAR(100),
    p_source_type VARCHAR(50) DEFAULT NULL
)
RETURNS TABLE (
    source_type VARCHAR(50),
    source_id TEXT,
    confidence_score NUMERIC(3,2),
    is_verified BOOLEAN,
    created_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        mcc.source_type,
        mcc.source_id,
        mcc.confidence_score,
        mcc.is_verified,
        mcc.created_at
    FROM public.map_custom_content mcc
    WHERE mcc.content_code = p_content_code
      AND (p_source_type IS NULL OR mcc.source_type = p_source_type)
    ORDER BY mcc.order_num, mcc.created_at DESC;
$$;


/*
 ***********************************************************************************************
 * FUNCTION: 필터링 조회 (진행중/예정/종료)
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.get_custom_contents_by_filter(
    p_content_type VARCHAR(30) DEFAULT NULL,
    p_city_code VARCHAR(96) DEFAULT NULL,
    p_status VARCHAR(20) DEFAULT 'ongoing',         -- ongoing, upcoming, ended, all
    p_is_free BOOLEAN DEFAULT NULL,
    p_categories TEXT[] DEFAULT NULL,
    p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
    id BIGINT,
    content_code VARCHAR(100),
    content_type VARCHAR(30),
    content_subtype VARCHAR(50),
    name TEXT,
    name_ko TEXT,
    venue_name TEXT,
    thumbnail_url TEXT,
    period_start DATE,
    period_end DATE,
    is_free BOOLEAN,
    categories TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        cc.id,
        cc.content_code,
        cc.content_type,
        cc.content_subtype,
        cc.name,
        cc.name_ko,
        cc.venue_name,
        cc.thumbnail_url,
        cc.period_start,
        cc.period_end,
        cc.is_free,
        cc.categories
    FROM public.custom_content cc
    WHERE cc.is_active = TRUE
      AND cc.is_display = TRUE
      AND (p_content_type IS NULL OR cc.content_type = p_content_type)
      AND (p_city_code IS NULL OR cc.city_code = p_city_code)
      AND (p_is_free IS NULL OR cc.is_free = p_is_free)
      AND (p_categories IS NULL OR cc.categories && p_categories)
      AND (
          p_status = 'all'
          OR (p_status = 'ongoing' AND (cc.is_permanent = TRUE OR (cc.period_start <= CURRENT_DATE AND (cc.period_end IS NULL OR cc.period_end >= CURRENT_DATE))))
          OR (p_status = 'upcoming' AND cc.period_start > CURRENT_DATE)
          OR (p_status = 'ended' AND cc.period_end < CURRENT_DATE)
      )
    ORDER BY 
        CASE WHEN p_status = 'upcoming' THEN cc.period_start END ASC,
        CASE WHEN p_status != 'upcoming' THEN cc.period_end END DESC NULLS LAST,
        cc.created_at DESC
    LIMIT p_limit;
$$;

COMMENT ON FUNCTION public.get_custom_contents_by_filter IS 
'상태별(진행중/예정/종료) 커스텀 콘텐츠 필터링 조회';
