/*
 * aiqna db for web service (Processing Logs)
 * Database Name 'aiqna'
 *
 * Created 2024-09-24
 * Updated 2025-12-01
 * 
 * 테이블 목록:
 *   1. processing_log_youtube_video    - YouTube 비디오 처리 로그
 *   2. processing_log_instagram_post   - Instagram 포스트 처리 로그
 *   3. processing_log_blog_post        - 블로그 포스트 처리 로그
 *   4. processing_log_text             - 텍스트 처리 로그
 * 
 * 공통 필드 구조:
 *   - processing_status: pending, processing, completed, failed (, partial)
 *   - is_error_occurred / error_message: 에러 상태
 *   - processing_started_at / processing_completed_at / last_processed_at: 처리 시간
 *   - retry_count / max_retry_count: 재시도 관리
 *   - source: 데이터 출처 식별자
 *   - priority: 우선순위 (0-10, 기본 5, 높을수록 먼저 처리)
 *   - assigned_worker: 배정된 워커 ID
 *   - created_at / updated_at: 시스템 타임스탬프
 */


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                    1. PROCESSING_LOG_YOUTUBE_VIDEO                        ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: processing_log_youtube_video
 ***********************************************************************************************
 * 설명: YouTube 비디오 처리 로그 (API 데이터 + Transcripts 처리 추적)
 * 
 * 처리 단계:
 *   [API 데이터] - 개별 상태 추적
 *     1. Fetch           → is_api_data_fetched
 *     2. AI Analyze      → is_api_data_analyzed
 *     3. Save to DB      → is_api_data_saved_to_db
 *     4. Save to Pinecone → is_api_data_saved_to_pinecone
 *     5. Summary → DB    → is_api_summary_saved_to_db
 *     6. Summary → Pinecone → is_api_summary_saved_to_pinecone
 * 
 *   [Transcripts] - 집계 상태 추적
 *     - 개별 상태는 youtube_video_transcript 테이블에서 관리
 *     - 이 테이블에서는 언어별 완료/실패 목록만 집계
 *     - youtube_video_transcript.processing_status 변경 시 트리거로 자동 동기화
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.processing_log_youtube_video (
    -- ========================================
    -- 기본 정보
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id VARCHAR(20) NOT NULL,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    -- pending: 대기, processing: 처리중, completed: 완료
    -- failed: 실패, partial: 부분완료 (일부 단계만 성공)
    
    -- ========================================
    -- 비디오 메타
    -- ========================================
    is_shorts BOOLEAN NOT NULL DEFAULT FALSE,

    -- ========================================
    -- API 데이터 처리: Step 1 - Fetch
    -- ========================================
    is_api_data_fetched BOOLEAN NOT NULL DEFAULT FALSE,
    is_error_occurred_api_data_fetched BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg_api_data_fetched TEXT NULL,

    -- ========================================
    -- API 데이터 처리: Step 2 - AI Analyze
    -- ========================================
    is_api_data_analyzed BOOLEAN NOT NULL DEFAULT FALSE,
    is_error_occurred_api_data_analyzed BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg_api_data_analyzed TEXT NULL,

    -- ========================================
    -- API 데이터 처리: Step 3 - Save to DB
    -- ========================================
    is_api_data_saved_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    is_error_occurred_api_data_saved_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg_api_data_saved_to_db TEXT NULL,

    -- ========================================
    -- API 데이터 처리: Step 4 - Save to Pinecone
    -- ========================================
    is_api_data_saved_to_pinecone BOOLEAN NOT NULL DEFAULT FALSE,
    is_error_occurred_api_data_saved_to_pinecone BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg_api_data_saved_to_pinecone TEXT NULL,

    -- ========================================
    -- API 데이터 처리: Step 5 - Summary Save to DB
    -- ========================================
    is_api_summary_saved_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    is_error_occurred_api_summary_saved_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg_api_summary_saved_to_db TEXT NULL,

    -- ========================================
    -- API 데이터 처리: Step 6 - Summary Save to Pinecone
    -- ========================================
    is_api_summary_saved_to_pinecone BOOLEAN NOT NULL DEFAULT FALSE,
    is_error_occurred_api_summary_saved_to_pinecone BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg_api_summary_saved_to_pinecone TEXT NULL,

    -- ========================================
    -- Transcripts 집계 상태
    -- (개별 상태는 youtube_video_transcript에서 관리)
    -- (트리거로 자동 동기화됨)
    -- ========================================
    is_transcript_exist BOOLEAN NULL,                     -- 자막 존재 여부
    
    -- 언어별 상태 배열
    transcript_total_lang_codes VARCHAR(12)[] NULL,            -- 전체 ['ko', 'en', 'ja']
    transcript_completed_lang_codes VARCHAR(12)[] NULL,        -- 완료 ['ko', 'en']
    transcript_failed_lang_codes VARCHAR(12)[] NULL,           -- 실패 ['ja']
    
    -- 카운트 (빠른 조회용)
    transcript_total_count SMALLINT NOT NULL DEFAULT 0,
    transcript_completed_count SMALLINT NOT NULL DEFAULT 0,
    transcript_failed_count SMALLINT NOT NULL DEFAULT 0,
    
    -- 전체 완료 플래그
    is_all_transcripts_completed BOOLEAN NOT NULL DEFAULT FALSE,

    -- ========================================
    -- 전체 에러 상태
    -- ========================================
    is_error_occurred BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg TEXT NULL,

    -- ========================================
    -- 처리 시간
    -- ========================================
    processing_started_at TIMESTAMPTZ NULL,
    processing_completed_at TIMESTAMPTZ NULL,
    last_processed_at TIMESTAMPTZ NULL,

    -- ========================================
    -- 재시도 및 워커
    -- ========================================
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    source VARCHAR(50) NULL,                              -- 데이터 출처 (admin, api, crawler 등)
    priority INTEGER NOT NULL DEFAULT 5,                  -- 0-10, 높을수록 먼저 처리
    assigned_worker VARCHAR(100) NULL,                    -- 처리 중인 워커 ID
    
    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT plyv_video_id_unique 
        UNIQUE (video_id),
    CONSTRAINT plyv_processing_status_check 
        CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed', 'partial')),
    CONSTRAINT plyv_processing_times_check 
        CHECK (processing_started_at IS NULL 
            OR processing_completed_at IS NULL 
            OR processing_completed_at >= processing_started_at),
    CONSTRAINT plyv_retry_count_check 
        CHECK (retry_count >= 0 AND retry_count <= max_retry_count),
    CONSTRAINT plyv_priority_check 
        CHECK (priority >= 0 AND priority <= 10),
    CONSTRAINT plyv_transcript_count_check
        CHECK (transcript_completed_count + transcript_failed_count <= transcript_total_count)
);

-- ========================================
-- 인덱스: processing_log_youtube_video
-- ========================================
-- video_id 조회용 (누락되어 있던 것)
CREATE INDEX IF NOT EXISTS idx_plyv_video_id 
    ON public.processing_log_youtube_video (video_id);

-- 상태별 조회용
CREATE INDEX IF NOT EXISTS idx_plyv_status 
    ON public.processing_log_youtube_video (processing_status);

-- 워커 큐: 대기 중 작업을 우선순위/생성일 기준으로 가져오기
CREATE INDEX IF NOT EXISTS idx_plyv_pending_priority 
    ON public.processing_log_youtube_video (priority DESC, created_at ASC) 
    WHERE processing_status = 'pending';

-- 에러 발생 건 필터링용
CREATE INDEX IF NOT EXISTS idx_plyv_error_occurred
    ON public.processing_log_youtube_video (is_error_occurred)
    WHERE is_error_occurred = TRUE;

-- 워커 배정된 작업 모니터링용
CREATE INDEX IF NOT EXISTS idx_plyv_assigned_worker
    ON public.processing_log_youtube_video (assigned_worker)
    WHERE assigned_worker IS NOT NULL 
    AND processing_status = 'processing';

-- 부분 완료 상태 조회용
CREATE INDEX IF NOT EXISTS idx_plyv_partial
    ON public.processing_log_youtube_video (processing_status, updated_at DESC)
    WHERE processing_status = 'partial';

-- ========================================
-- RLS: processing_log_youtube_video
-- ========================================
ALTER TABLE public.processing_log_youtube_video ENABLE ROW LEVEL SECURITY;

CREATE POLICY "processing_log_youtube_video is visible to everyone" 
    ON public.processing_log_youtube_video FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage processing_log_youtube_video" 
    ON public.processing_log_youtube_video FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION update_plyv_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_plyv_updated_at
    BEFORE UPDATE ON public.processing_log_youtube_video
    FOR EACH ROW
    EXECUTE FUNCTION update_plyv_updated_at();


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                    2. PROCESSING_LOG_INSTAGRAM_POST                       ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: processing_log_instagram_post
 ***********************************************************************************************
 * 설명: Instagram 포스트 단위 처리 로그
 * 
 * 처리 단계:
 *   1. Fetch     → is_data_fetched (HTML / API 등)
 *   2. Pinecone  → is_pinecone_processed (벡터화)
 * 
 * 특징:
 *   - instagram_post_url 기준 1:1 추적 (UNIQUE)
 *   - 단일 처리 흐름이므로 partial 상태 없음
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.processing_log_instagram_post (
    -- ========================================
    -- 기본 정보
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instagram_post_url VARCHAR(1023) NOT NULL UNIQUE,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    -- pending, processing, completed, failed (partial 없음)

    -- ========================================
    -- 처리 플래그
    -- ========================================
    is_data_fetched BOOLEAN NOT NULL DEFAULT FALSE,
    is_pinecone_processed BOOLEAN NOT NULL DEFAULT FALSE,

    -- ========================================
    -- 전체 에러 상태
    -- ========================================
    is_error_occurred BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg TEXT NULL,

    -- ========================================
    -- 처리 시간
    -- ========================================
    processing_started_at TIMESTAMPTZ NULL,
    processing_completed_at TIMESTAMPTZ NULL,
    last_processed_at TIMESTAMPTZ NULL,

    -- ========================================
    -- 재시도 및 워커
    -- ========================================
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    source VARCHAR(50) NULL,
    priority INTEGER NOT NULL DEFAULT 5,
    assigned_worker VARCHAR(100) NULL,

    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT plip_processing_status_check 
        CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT plip_processing_times_check 
        CHECK (
            processing_started_at IS NULL 
            OR processing_completed_at IS NULL 
            OR processing_completed_at >= processing_started_at
        ),
    CONSTRAINT plip_retry_count_check
        CHECK (retry_count >= 0 AND retry_count <= max_retry_count),
    CONSTRAINT plip_priority_check
        CHECK (priority >= 0 AND priority <= 10)
);

-- ========================================
-- 인덱스: processing_log_instagram_post
-- ========================================
CREATE INDEX IF NOT EXISTS idx_plip_status 
    ON public.processing_log_instagram_post (processing_status);

CREATE INDEX IF NOT EXISTS idx_plip_pending_priority 
    ON public.processing_log_instagram_post (priority DESC, created_at ASC)
    WHERE processing_status = 'pending';

CREATE INDEX IF NOT EXISTS idx_plip_error_occurred
    ON public.processing_log_instagram_post (is_error_occurred)
    WHERE is_error_occurred = TRUE;

CREATE INDEX IF NOT EXISTS idx_plip_assigned_worker
    ON public.processing_log_instagram_post (assigned_worker)
    WHERE assigned_worker IS NOT NULL
        AND processing_status = 'processing';

CREATE INDEX IF NOT EXISTS idx_plip_instagram_post_url
    ON public.processing_log_instagram_post (instagram_post_url);

-- ========================================
-- RLS: processing_log_instagram_post
-- ========================================
ALTER TABLE public.processing_log_instagram_post ENABLE ROW LEVEL SECURITY;

CREATE POLICY "processing_log_instagram_post is visible to everyone" 
    ON public.processing_log_instagram_post
    FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage processing_log_instagram_post" 
    ON public.processing_log_instagram_post
    FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION update_plip_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_plip_updated_at
    BEFORE UPDATE ON public.processing_log_instagram_post
    FOR EACH ROW
    EXECUTE FUNCTION update_plip_updated_at();


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                      3. PROCESSING_LOG_BLOG_POST                          ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: processing_log_blog_post
 ***********************************************************************************************
 * 설명: 블로그 포스트 단위 처리 로그
 * 
 * 처리 단계:
 *   1. Fetch     → is_data_fetched (HTML / RSS / API)
 *   2. Pinecone  → is_pinecone_processed (벡터화)
 * 
 * 특징:
 *   - blog_post_url 기준 1:1 추적 (UNIQUE)
 *   - 단일 처리 흐름이므로 partial 상태 없음
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.processing_log_blog_post (
    -- ========================================
    -- 기본 정보
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_post_url VARCHAR(1023) NOT NULL UNIQUE,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'pending',

    -- ========================================
    -- 처리 플래그
    -- ========================================
    is_data_fetched BOOLEAN NOT NULL DEFAULT FALSE,
    is_pinecone_processed BOOLEAN NOT NULL DEFAULT FALSE,

    -- ========================================
    -- 전체 에러 상태
    -- ========================================
    is_error_occurred BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg TEXT NULL,

    -- ========================================
    -- 처리 시간
    -- ========================================
    processing_started_at TIMESTAMPTZ NULL,
    processing_completed_at TIMESTAMPTZ NULL,
    last_processed_at TIMESTAMPTZ NULL,

    -- ========================================
    -- 재시도 및 워커
    -- ========================================
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    source VARCHAR(50) NULL,
    priority INTEGER NOT NULL DEFAULT 5,
    assigned_worker VARCHAR(100) NULL,

    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT plbp_processing_status_check 
        CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT plbp_processing_times_check 
        CHECK (
            processing_started_at IS NULL 
            OR processing_completed_at IS NULL 
            OR processing_completed_at >= processing_started_at
        ),
    CONSTRAINT plbp_retry_count_check
        CHECK (retry_count >= 0 AND retry_count <= max_retry_count),
    CONSTRAINT plbp_priority_check
        CHECK (priority >= 0 AND priority <= 10)
);

-- ========================================
-- 인덱스: processing_log_blog_post
-- ========================================
CREATE INDEX IF NOT EXISTS idx_plbp_status 
    ON public.processing_log_blog_post (processing_status);

CREATE INDEX IF NOT EXISTS idx_plbp_pending_priority
    ON public.processing_log_blog_post (priority DESC, created_at ASC)
    WHERE processing_status = 'pending';

CREATE INDEX IF NOT EXISTS idx_plbp_error_occurred
    ON public.processing_log_blog_post (is_error_occurred)
    WHERE is_error_occurred = TRUE;

CREATE INDEX IF NOT EXISTS idx_plbp_assigned_worker
    ON public.processing_log_blog_post (assigned_worker)
    WHERE assigned_worker IS NOT NULL
        AND processing_status = 'processing';

CREATE INDEX IF NOT EXISTS idx_plbp_blog_post_url
    ON public.processing_log_blog_post (blog_post_url);

-- ========================================
-- RLS: processing_log_blog_post
-- ========================================
ALTER TABLE public.processing_log_blog_post ENABLE ROW LEVEL SECURITY;

CREATE POLICY "processing_log_blog_post is visible to everyone" 
    ON public.processing_log_blog_post
    FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage processing_log_blog_post" 
    ON public.processing_log_blog_post
    FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION update_plbp_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_plbp_updated_at
    BEFORE UPDATE ON public.processing_log_blog_post
    FOR EACH ROW
    EXECUTE FUNCTION update_plbp_updated_at();


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                        4. PROCESSING_LOG_TEXT                             ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: processing_log_text
 ***********************************************************************************************
 * 설명: 텍스트 단위 처리 로그
 * 
 * 처리 단계:
 *   1. Pinecone  → is_pinecone_processed (벡터화)
 * 
 * 특징:
 *   - hash_key 기반 중복 방지 (SHA256 등)
 *   - 텍스트 직접 저장 없음 (해시로만 식별)
 *   - 가장 단순한 처리 흐름
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.processing_log_text (
    -- ========================================
    -- 기본 정보
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash_key VARCHAR(64) NOT NULL UNIQUE,                 -- SHA256 해시 (64자)
    processing_status VARCHAR(20) NOT NULL DEFAULT 'pending',

    -- ========================================
    -- 처리 플래그
    -- ========================================
    is_pinecone_processed BOOLEAN NOT NULL DEFAULT FALSE,

    -- ========================================
    -- 전체 에러 상태
    -- ========================================
    is_error_occurred BOOLEAN NOT NULL DEFAULT FALSE,
    error_msg TEXT NULL,

    -- ========================================
    -- 처리 시간
    -- ========================================
    processing_started_at TIMESTAMPTZ NULL,
    processing_completed_at TIMESTAMPTZ NULL,
    last_processed_at TIMESTAMPTZ NULL,

    -- ========================================
    -- 재시도 및 워커
    -- ========================================
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    source VARCHAR(50) NULL,
    priority INTEGER NOT NULL DEFAULT 5,
    assigned_worker VARCHAR(100) NULL,

    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT plt_processing_status_check 
        CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT plt_processing_times_check 
        CHECK (
            processing_started_at IS NULL
            OR processing_completed_at IS NULL
            OR processing_completed_at >= processing_started_at
        ),
    CONSTRAINT plt_retry_count_check
        CHECK (retry_count >= 0 AND retry_count <= max_retry_count),
    CONSTRAINT plt_priority_check
        CHECK (priority >= 0 AND priority <= 10)
);

-- ========================================
-- 인덱스: processing_log_text
-- ========================================
CREATE INDEX IF NOT EXISTS idx_plt_status
    ON public.processing_log_text (processing_status);

CREATE INDEX IF NOT EXISTS idx_plt_pending_priority
    ON public.processing_log_text (priority DESC, created_at ASC)
    WHERE processing_status = 'pending';

CREATE INDEX IF NOT EXISTS idx_plt_error_occurred
    ON public.processing_log_text (is_error_occurred)
    WHERE is_error_occurred = TRUE;

CREATE INDEX IF NOT EXISTS idx_plt_assigned_worker
    ON public.processing_log_text (assigned_worker)
    WHERE assigned_worker IS NOT NULL
      AND processing_status = 'processing';

CREATE INDEX IF NOT EXISTS idx_plt_hash_key
    ON public.processing_log_text (hash_key);

-- ========================================
-- RLS: processing_log_text
-- ========================================
ALTER TABLE public.processing_log_text ENABLE ROW LEVEL SECURITY;

CREATE POLICY "processing_log_text is visible to everyone"
    ON public.processing_log_text
    FOR SELECT
    TO authenticated, anon
    USING (TRUE);

CREATE POLICY "Service role can manage processing_log_text"
    ON public.processing_log_text
    FOR ALL
    TO service_role
    USING (TRUE)
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION update_plt_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_plt_updated_at
    BEFORE UPDATE ON public.processing_log_text
    FOR EACH ROW
    EXECUTE FUNCTION update_plt_updated_at();

