/*
 * aiqna db for web service (Neighborhoods with numeric PK)
 * Database Name 'aiqna'
 *
 * Created 2024-10-12
 * Updated 2025-10-25
 */

-- 필요 확장 (이미 설치되어 있으면 생략 가능)
-- CREATE EXTENSION IF NOT EXISTS postgis;
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;


--------------------------------------------------------------------------------
-- TABLE: neighborhoods
--------------------------------------------------------------------------------
CREATE TABLE public.neighborhoods (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ← 숫자 PK
  country_code    VARCHAR(2)    NULL,
  city_code       VARCHAR(96)   NULL,

  name_en         VARCHAR(100)  NOT NULL,
  name_native     VARCHAR(100)  NULL,
  name_ko         VARCHAR(100)  NULL,
  order_num       SMALLINT      NOT NULL DEFAULT 0,

  description_en      VARCHAR(1023) NULL,
  description_native  VARCHAR(1023) NULL,

  google_place_id VARCHAR(63)   NULL,
  youtube_ch_id   VARCHAR(48)   NULL,
  instagram_id    VARCHAR(48)   NULL,

  -- 위도/경도
  latitude   NUMERIC(10, 8) NULL,
  longitude  NUMERIC(11, 8) NULL,

  -- 자동 생성되는 지리 객체 컬럼
  location GEOGRAPHY(POINT, 4326)
    GENERATED ALWAYS AS (
      CASE 
        WHEN latitude IS NOT NULL AND longitude IS NOT NULL 
        THEN geography(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326))
        ELSE NULL
      END
    ) STORED,

  radius_m        INTEGER       NULL,
  address_en      VARCHAR(255)  NULL,
  address_native  VARCHAR(255)  NULL,
  google_map_url  VARCHAR(255)  NULL,
  naver_map_url   VARCHAR(255)  NULL,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by   VARCHAR(511) NULL,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
  deactivated_at TIMESTAMPTZ NULL,
  deactivated_by VARCHAR(511) NULL,
  is_display   BOOLEAN     NOT NULL DEFAULT TRUE,

  thumbnail_main_1 VARCHAR(1023) NULL,
  thumbnail_main_2 VARCHAR(1023) NULL,
  thumbnail_main_3 VARCHAR(1023) NULL,
  thumbnail_main_4 VARCHAR(1023) NULL,
  thumbnail_main_5 VARCHAR(1023) NULL,

  thumbnail_1      VARCHAR(1023) NULL,
  thumbnail_2      VARCHAR(1023) NULL,
  thumbnail_3      VARCHAR(1023) NULL,
  thumbnail_4      VARCHAR(1023) NULL,
  thumbnail_5      VARCHAR(1023) NULL,

  thumbnail_vertical_1 VARCHAR(1023) NULL,
  thumbnail_vertical_2 VARCHAR(1023) NULL,
  thumbnail_vertical_3 VARCHAR(1023) NULL,
  thumbnail_vertical_4 VARCHAR(1023) NULL,
  thumbnail_vertical_5 VARCHAR(1023) NULL,

  -- FK
  CONSTRAINT neighborhoods_country_code_fkey
    FOREIGN KEY (country_code)
    REFERENCES public.countries (country_code)
    ON UPDATE CASCADE ON DELETE CASCADE,

  CONSTRAINT neighborhoods_city_code_fkey
    FOREIGN KEY (city_code)
    REFERENCES public.cities (city_code)
    ON UPDATE CASCADE ON DELETE CASCADE,

  -- 값 검증
  CONSTRAINT neighborhoods_radius_m_check CHECK (radius_m IS NULL OR radius_m >= 0),
  CONSTRAINT neighborhoods_latitude_check CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
  CONSTRAINT neighborhoods_longitude_check CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
  CONSTRAINT neighborhoods_order_num_check CHECK (order_num >= 0)
) TABLESPACE pg_default;

-- INDEXES
CREATE INDEX IF NOT EXISTS neighborhoods_city_order_idx
  ON public.neighborhoods (city_code, order_num, id);

CREATE INDEX IF NOT EXISTS neighborhoods_country_idx
  ON public.neighborhoods (country_code);

CREATE INDEX IF NOT EXISTS neighborhoods_city_active_display_idx
  ON public.neighborhoods (city_code, is_active, is_display)
  WHERE is_active = TRUE AND is_display = TRUE;

CREATE INDEX IF NOT EXISTS neighborhoods_is_active_idx
  ON public.neighborhoods (is_active, order_num)
  WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS neighborhoods_location_gist_idx
  ON public.neighborhoods USING GIST (location)
  WHERE location IS NOT NULL;

CREATE INDEX IF NOT EXISTS neighborhoods_lat_lng_idx
  ON public.neighborhoods (latitude, longitude)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

CREATE INDEX IF NOT EXISTS neighborhoods_name_en_trgm_idx
  ON public.neighborhoods USING gin (name_en gin_trgm_ops);

CREATE INDEX IF NOT EXISTS neighborhoods_name_ko_trgm_idx
  ON public.neighborhoods USING gin (name_ko gin_trgm_ops)
  WHERE name_ko IS NOT NULL;

CREATE INDEX IF NOT EXISTS neighborhoods_name_native_trgm_idx
  ON public.neighborhoods USING gin (name_native gin_trgm_ops)
  WHERE name_native IS NOT NULL;

-- RLS
ALTER TABLE public.neighborhoods ENABLE ROW LEVEL SECURITY;

CREATE POLICY "neighborhoods are visible to everyone"
  ON public.neighborhoods FOR SELECT 
  TO authenticated, anon 
  USING (TRUE);

CREATE POLICY "Service role can manage neighborhoods"
  ON public.neighborhoods FOR ALL 
  TO service_role 
  USING (TRUE) 
  WITH CHECK (TRUE);

-- TRIGGER
CREATE TRIGGER trigger_update_neighborhoods_updated_at
  BEFORE UPDATE ON public.neighborhoods
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();



--------------------------------------------------------------------------------
-- TABLE: neighborhood_i18n  (PK: (neighborhood_id, lang_code))
--------------------------------------------------------------------------------
CREATE TABLE public.neighborhood_i18n (
  neighborhood_id   BIGINT       NOT NULL,          -- ← 참조 ID
  lang_code         VARCHAR(8)   NOT NULL,
  name_i18n         VARCHAR(255) NOT NULL,
  description_i18n  VARCHAR(1023) NULL,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT neighborhood_i18n_pkey PRIMARY KEY (neighborhood_id, lang_code),
  CONSTRAINT neighborhood_i18n_neighborhood_id_fkey
    FOREIGN KEY (neighborhood_id) 
    REFERENCES public.neighborhoods (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT neighborhood_i18n_lang_code_fkey
    FOREIGN KEY (lang_code) 
    REFERENCES public.languages (lang_code)
    ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

-- INDEXES
CREATE INDEX IF NOT EXISTS neighborhood_i18n_name_trgm_idx
  ON public.neighborhood_i18n USING gin (name_i18n gin_trgm_ops);

CREATE INDEX IF NOT EXISTS neighborhood_i18n_lang_idx
  ON public.neighborhood_i18n (lang_code);

-- RLS
ALTER TABLE public.neighborhood_i18n ENABLE ROW LEVEL SECURITY;

CREATE POLICY "neighborhood_i18n are visible to everyone"
  ON public.neighborhood_i18n FOR SELECT 
  TO authenticated, anon 
  USING (TRUE);

CREATE POLICY "Service role can manage neighborhood_i18n"
  ON public.neighborhood_i18n FOR ALL 
  TO service_role 
  USING (TRUE) 
  WITH CHECK (TRUE);

-- TRIGGER
CREATE TRIGGER trigger_update_neighborhood_i18n_updated_at
  BEFORE UPDATE ON public.neighborhood_i18n
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();



--------------------------------------------------------------------------------
-- TABLE: map_neighborhood_search_keywords (PK: (neighborhood_id, search_keyword))
--------------------------------------------------------------------------------
CREATE TABLE public.map_neighborhood_search_keywords (
  neighborhood_id BIGINT      NOT NULL,
  search_keyword  VARCHAR(100) NOT NULL,
  CONSTRAINT map_neighborhood_search_keywords_pkey 
    PRIMARY KEY (neighborhood_id, search_keyword),
  CONSTRAINT map_neighborhood_search_keywords_neighborhood_id_fkey 
    FOREIGN KEY (neighborhood_id) 
    REFERENCES public.neighborhoods (id) 
    ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.map_neighborhood_search_keywords ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_mnsq_neighborhood_id
  ON public.map_neighborhood_search_keywords (neighborhood_id);

CREATE POLICY "map_neighborhood_search_keywords are visible to everyone" 
  ON public.map_neighborhood_search_keywords FOR SELECT 
  TO authenticated, anon 
  USING (TRUE);

CREATE POLICY "Service role can manage map_neighborhood_search_keywords" 
  ON public.map_neighborhood_search_keywords FOR ALL 
  TO service_role 
  USING (TRUE) 
  WITH CHECK (TRUE);



--------------------------------------------------------------------------------
-- TABLE: map_neighborhood (PK: (neighborhood_id, source_type, source_id))
--------------------------------------------------------------------------------
CREATE TABLE public.map_neighborhood (
  neighborhood_id BIGINT      NOT NULL,             -- ← 참조 ID
  source_type     VARCHAR(50) NOT NULL,
  source_id       VARCHAR(1023) NOT NULL,

  -- AI 추출 정보
  confidence_score   NUMERIC(3, 2) NULL,  -- 0.00 ~ 1.00
  extracted_at       TIMESTAMPTZ DEFAULT NOW(),
  extraction_method  VARCHAR(50) NULL,
  
  -- 관리 정보
  is_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at  TIMESTAMPTZ NULL,
  verified_by  VARCHAR(511) NULL,
  
  is_selected  BOOLEAN NOT NULL DEFAULT FALSE,
  order_num    INTEGER NOT NULL DEFAULT 0,
  added_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT map_neighborhood_pkey
    PRIMARY KEY (neighborhood_id, source_type, source_id),

  CONSTRAINT map_neighborhood_neighborhood_id_fkey
    FOREIGN KEY (neighborhood_id) 
    REFERENCES public.neighborhoods (id)
    ON UPDATE CASCADE ON DELETE CASCADE,

  CONSTRAINT map_neighborhood_source_type_check 
    CHECK (source_type IN ('youtube_video', 'instagram_post', 'blog_post', 'text')),
  
  CONSTRAINT map_neighborhood_order_num_check CHECK (order_num >= 0),
  CONSTRAINT map_neighborhood_confidence_check 
    CHECK (confidence_score IS NULL OR (confidence_score BETWEEN 0 AND 1))
) TABLESPACE pg_default;

-- INDEXES
CREATE INDEX IF NOT EXISTS map_neighborhood_id_order_idx
  ON public.map_neighborhood (neighborhood_id, order_num, source_id);

CREATE INDEX IF NOT EXISTS map_neighborhood_id_added_idx
  ON public.map_neighborhood (neighborhood_id, added_at DESC, source_id);

CREATE INDEX IF NOT EXISTS map_neighborhood_selected_idx
  ON public.map_neighborhood (neighborhood_id, order_num, added_at DESC)
  WHERE is_selected = TRUE;

CREATE INDEX IF NOT EXISTS map_neighborhood_verified_idx
  ON public.map_neighborhood (neighborhood_id, confidence_score DESC)
  WHERE is_verified = TRUE;

CREATE INDEX IF NOT EXISTS map_neighborhood_source_idx
  ON public.map_neighborhood (source_type, source_id, neighborhood_id);

CREATE INDEX IF NOT EXISTS map_neighborhood_source_type_idx
  ON public.map_neighborhood (source_type, added_at DESC);

CREATE INDEX IF NOT EXISTS map_neighborhood_confidence_idx
  ON public.map_neighborhood (confidence_score DESC)
  WHERE confidence_score >= 0.8;

-- RLS
ALTER TABLE public.map_neighborhood ENABLE ROW LEVEL SECURITY;

CREATE POLICY "map_neighborhood are visible to everyone"
  ON public.map_neighborhood FOR SELECT 
  TO authenticated, anon 
  USING (TRUE);

CREATE POLICY "Service role can manage map_neighborhood"
  ON public.map_neighborhood FOR ALL 
  TO service_role 
  USING (TRUE) 
  WITH CHECK (TRUE);

-- TRIGGER
CREATE TRIGGER trigger_update_map_neighborhood_updated_at
  BEFORE UPDATE ON public.map_neighborhood
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();



--------------------------------------------------------------------------------
-- FUNCTION: upsert_neighborhood_mapping (ID 버전)
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.upsert_neighborhood_mapping(
    p_neighborhood_id BIGINT,
    p_source_type VARCHAR(50),
    p_source_id   VARCHAR(1023),
    p_confidence_score NUMERIC(3, 2) DEFAULT NULL,
    p_extraction_method VARCHAR(50) DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
    INSERT INTO public.map_neighborhood (
        neighborhood_id,
        source_type,
        source_id,
        confidence_score,
        extraction_method,
        extracted_at
    ) VALUES (
        p_neighborhood_id,
        p_source_type,
        p_source_id,
        p_confidence_score,
        p_extraction_method,
        NOW()
    )
    ON CONFLICT (neighborhood_id, source_type, source_id) DO UPDATE SET
        confidence_score = EXCLUDED.confidence_score,
        extraction_method = EXCLUDED.extraction_method,
        extracted_at = NOW(),
        updated_at = NOW();
END;
$$;



--------------------------------------------------------------------------------
-- FUNCTION: get_neighborhoods_for_content (ID 반환)
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_neighborhoods_for_content(
    p_source_type VARCHAR(50),
    p_source_id   VARCHAR(1023)
)
RETURNS TABLE (
    neighborhood_id BIGINT,
    name_en VARCHAR(100),
    name_ko VARCHAR(100),
    city_code VARCHAR(96),
    confidence_score NUMERIC(3, 2),
    is_verified BOOLEAN
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        n.id AS neighborhood_id,
        n.name_en,
        n.name_ko,
        n.city_code,
        ms.confidence_score,
        ms.is_verified
    FROM public.map_neighborhood ms
    JOIN public.neighborhoods n ON ms.neighborhood_id = n.id
    WHERE ms.source_type = p_source_type
      AND ms.source_id = p_source_id
    ORDER BY ms.confidence_score DESC NULLS LAST, ms.order_num;
$$;



--------------------------------------------------------------------------------
-- FUNCTION: get_content_for_neighborhood (ID 입력)
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_content_for_neighborhood(
    p_neighborhood_id BIGINT,
    p_source_type VARCHAR(50) DEFAULT NULL,
    p_verified_only BOOLEAN DEFAULT FALSE
)
RETURNS TABLE (
    source_type VARCHAR(50),
    source_id VARCHAR(1023),
    confidence_score NUMERIC(3, 2),
    is_verified BOOLEAN,
    added_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        ms.source_type,
        ms.source_id,
        ms.confidence_score,
        ms.is_verified,
        ms.added_at
    FROM public.map_neighborhood ms
    WHERE ms.neighborhood_id = p_neighborhood_id
      AND (p_source_type IS NULL OR ms.source_type = p_source_type)
      AND (NOT p_verified_only OR ms.is_verified = TRUE)
    ORDER BY ms.order_num, ms.added_at DESC;
$$;



--------------------------------------------------------------------------------
-- FUNCTION: get_neighborhoods_by_city (ID 반환)
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_neighborhoods_by_city(
    p_city_code VARCHAR(96),
    p_active_only BOOLEAN DEFAULT TRUE
)
RETURNS TABLE (
    neighborhood_id BIGINT,
    name_en VARCHAR(100),
    name_ko VARCHAR(100),
    name_native VARCHAR(100),
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    order_num SMALLINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT 
        n.id AS neighborhood_id,
        n.name_en,
        n.name_ko,
        n.name_native,
        n.latitude,
        n.longitude,
        n.order_num
    FROM public.neighborhoods n
    WHERE n.city_code = p_city_code
      AND (NOT p_active_only OR (n.is_active = TRUE AND n.is_display = TRUE))
    ORDER BY n.order_num, n.id;
$$;
