/*
 * aiqna db for web service (Text Tables)
 * Database Name 'aiqna'
 *
 * Created 2024-09-24
 * Updated 2025-12-01
 * 
 * 테이블:
 *   1. text_content           - 사용자 입력 텍스트 콘텐츠
 * 
 * 함수:
 *   - upsert_text_content()             - 텍스트 데이터 저장
 *   - upsert_text_content_ai_analysis() - AI 분석 결과 저장
 */





-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                          1. TEXT_CONTENT 테이블                            ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * TABLE: text_content
 ***********************************************************************************************
 * 설명: 사용자가 직접 입력한 텍스트 콘텐츠 저장
 * 데이터 소스: 사용자 직접 입력, 복사/붙여넣기
 * 
 * 특징:
 *   - hash_key로 중복 방지 (SHA256)
 *   - 출처 URL 선택적 저장
 *   - YouTube/Instagram/Blog와 동일한 AI 분석 결과 구조
 * 
 * 섹션:
 *   - 기본 정보 (제목, 본문, 해시)
 *   - 출처 정보 (선택적)
 *   - 텍스트 통계
 *   - AI 분석 결과 (ai_*)
 ***********************************************************************************************
 */
CREATE TABLE IF NOT EXISTS public.text_content (
    -- ========================================
    -- 기본 키
    -- ========================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash_key VARCHAR(64) NOT NULL,              -- SHA256 해시 (중복 방지)
    
    -- ========================================
    -- 텍스트 기본 정보
    -- ========================================
    title TEXT NULL,                            -- 제목 (선택)
    content TEXT NOT NULL,                      -- 본문 내용 (필수)
    content_type VARCHAR(50) NOT NULL DEFAULT 'plain', -- plain, markdown, html
    language VARCHAR(10) NULL,                  -- 언어 코드 (ko, en, ja 등)
    
    -- ========================================
    -- 출처 정보 (선택적)
    -- ========================================
    source_url TEXT NULL,                       -- 출처 URL
    source_name VARCHAR(255) NULL,              -- 출처 이름
    source_type VARCHAR(50) NULL,               -- article, document, note, other
    author_name VARCHAR(255) NULL,              -- 작성자
    published_date TIMESTAMPTZ NULL,            -- 원본 게시 일시
    
    -- ========================================
    -- 텍스트 통계
    -- ========================================
    char_count INTEGER NOT NULL DEFAULT 0,      -- 문자 수
    word_count INTEGER NOT NULL DEFAULT 0,      -- 단어 수
    line_count INTEGER NOT NULL DEFAULT 0,      -- 줄 수
    
    -- ========================================
    -- AI 분석 결과 - 콘텐츠 요약
    -- ========================================
    ai_summary TEXT NULL,                       -- 텍스트 전체 요약
    ai_key_points TEXT[] NULL,                  -- 핵심 포인트 배열
    
    ai_meta_category TEXT[] NULL,               -- 카테고리 ['맛집', '관광', '카페']
    ai_meta_influencer TEXT[] NULL,             -- 언급된 인플루언서
    ai_meta_season TEXT[] NULL,                 -- 적합한 계절 ['봄', '가을']
    ai_meta_time_of_day TEXT[] NULL,            -- 적합한 시간대 ['아침', '저녁']
    ai_meta_activity_type TEXT[] NULL,          -- 활동 유형 ['데이트', '가족여행', '혼행']
    ai_meta_special_tag TEXT[] NULL,            -- 특수 태그 ['여행정보', '맛집리스트', '일기']
    ai_meta_kpop TEXT[] NULL,                   -- K-POP 관련 태그 ['BTS', 'BLACKPINK', 'EXO']
    ai_meta_target_age TEXT[] NULL,             -- 타겟 연령 ['20대', '30대', '40대', '50대', '60대 이상']
    ai_meta_target_audience TEXT[] NULL,        -- 타겟 ['20대', '커플', '외국인']
    ai_meta_landmark TEXT[] NULL,               -- 랜드마크 ['광화문', '경복궁', '창덕궁']
    ai_meta_city TEXT[] NULL,                   -- 도시 ['서울', '부산', '인천']
    ai_meta_country TEXT[] NULL,                -- 국가 ['대한민국', '미국', '일본']
    ai_meta_district TEXT[] NULL,               -- 구 ['종로구', '강남구', '서초구']
    ai_meta_neighborhood TEXT[] NULL,           -- 동 ['세종로', '강남동', '서초동']
    ai_meta_place TEXT[] NULL,                  -- 장소 ['경복궁', '을지로 골뱅이', '카페 온마']
    
    -- ========================================
    -- AI 분석 결과 - 장소별 상세 정보
    -- ========================================
    ai_places JSONB NULL,                       -- 장소 상세 정보
    ai_places_count SMALLINT NULL,              -- 장소 개수 (쿼리 최적화용)
    /*
    ai_places 구조: (다른 테이블과 동일)
    [
        {
            "place_name": "을지로 골뱅이",
            "place_name_en": "Euljiro Golbaengi",
            "place_name_native": null,
            "place_type": "restaurant",
            "country": "KR",
            "city": "서울",
            "district": "중구",
            "neighborhood": "을지로",
            "landmark": "을지로3가역 근처",
            "address": "서울특별시 중구 을지로 123",
            "latitude": 37.5665,
            "longitude": 126.9780,
            "period": null,
            "start_date": null,
            "end_date": null,
            "operation_hours": "17:00-24:00",
            "prices": {"골뱅이무침": 15000, "소주": 5000, "currency": "KRW"},
            "recommend_menu": ["골뱅이무침", "계란찜"],
            "travel_tips": ["예약 필수", "웨이팅 있음"],
            "notice": "일요일 휴무",
            "review_summary": "을지로 맛집으로 유명",
            "reservation_required": true,
            "order_in_content": 1
        }
    ]
    */
    
    -- ========================================
    -- AI 분석 메타
    -- ========================================
    ai_analyzed_at TIMESTAMPTZ NULL,
    ai_model VARCHAR(50) NULL,
    ai_confidence NUMERIC(3,2) NULL,            -- 0.00 ~ 1.00
    
    -- ========================================
    -- 시스템 관리
    -- ========================================
    metadata_json JSONB NULL,                   -- 추가 메타데이터
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    
    -- ========================================
    -- 시스템 타임스탬프
    -- ========================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_processed_at TIMESTAMPTZ NULL,

    -- ========================================
    -- 제약조건
    -- ========================================
    CONSTRAINT tc_hash_key_unique 
        UNIQUE (hash_key),
    CONSTRAINT tc_content_not_empty 
        CHECK (LENGTH(TRIM(content)) > 0),
    CONSTRAINT tc_content_type_check 
        CHECK (content_type IN ('plain', 'markdown', 'html')),
    CONSTRAINT tc_source_type_check 
        CHECK (source_type IS NULL OR source_type IN ('article', 'document', 'note', 'other')),
    CONSTRAINT tc_char_count_check 
        CHECK (char_count >= 0),
    CONSTRAINT tc_word_count_check 
        CHECK (word_count >= 0),
    CONSTRAINT tc_line_count_check 
        CHECK (line_count >= 0),
    CONSTRAINT tc_ai_places_count_check
        CHECK (ai_places_count IS NULL OR ai_places_count >= 0),
    CONSTRAINT tc_ai_confidence_check
        CHECK (ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)),
    CONSTRAINT tc_deleted_logic_check
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) 
            OR (is_deleted = TRUE AND deleted_at IS NOT NULL)
        )
);

-- ========================================
-- 인덱스: text_content
-- ========================================
-- 기본 검색 인덱스
CREATE INDEX IF NOT EXISTS idx_tc_hash_key 
    ON public.text_content (hash_key);
CREATE INDEX IF NOT EXISTS idx_tc_created_at 
    ON public.text_content (created_at);
CREATE INDEX IF NOT EXISTS idx_tc_content_type 
    ON public.text_content (content_type);
CREATE INDEX IF NOT EXISTS idx_tc_language 
    ON public.text_content (language);
CREATE INDEX IF NOT EXISTS idx_tc_source_type 
    ON public.text_content (source_type);

-- 조건부 인덱스 (Partial Index)
CREATE INDEX IF NOT EXISTS idx_tc_is_active 
    ON public.text_content (is_active) 
    WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_tc_is_deleted 
    ON public.text_content (is_deleted) 
    WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_tc_has_source_url 
    ON public.text_content (source_url) 
    WHERE source_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tc_ai_analyzed_at
    ON public.text_content (ai_analyzed_at)
    WHERE ai_analyzed_at IS NOT NULL;

-- 배열 컬럼 GIN 인덱스
CREATE INDEX IF NOT EXISTS idx_tc_ai_meta_category_gin
    ON public.text_content USING GIN (ai_meta_category);
CREATE INDEX IF NOT EXISTS idx_tc_ai_meta_activity_type_gin
    ON public.text_content USING GIN (ai_meta_activity_type);
CREATE INDEX IF NOT EXISTS idx_tc_ai_meta_special_tag_gin
    ON public.text_content USING GIN (ai_meta_special_tag);
CREATE INDEX IF NOT EXISTS idx_tc_ai_meta_city_gin
    ON public.text_content USING GIN (ai_meta_city);
CREATE INDEX IF NOT EXISTS idx_tc_ai_meta_landmark_gin
    ON public.text_content USING GIN (ai_meta_landmark);
CREATE INDEX IF NOT EXISTS idx_tc_ai_meta_place_gin
    ON public.text_content USING GIN (ai_meta_place);

-- JSONB GIN 인덱스
CREATE INDEX IF NOT EXISTS idx_tc_ai_places_gin 
    ON public.text_content USING GIN (ai_places);
CREATE INDEX IF NOT EXISTS idx_tc_metadata_json_gin 
    ON public.text_content USING GIN (metadata_json);

-- 전체 텍스트 검색 인덱스
CREATE INDEX IF NOT EXISTS idx_tc_text_search_gin 
    ON public.text_content USING GIN (
        to_tsvector('simple', 
            COALESCE(title, '') || ' ' || 
            COALESCE(content, '')
        )
    );

-- ========================================
-- RLS: text_content
-- ========================================
ALTER TABLE public.text_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "text_content is visible to everyone" 
    ON public.text_content FOR SELECT 
    TO authenticated, anon 
    USING (TRUE);

CREATE POLICY "Service role can manage text_content" 
    ON public.text_content FOR ALL 
    TO service_role 
    USING (TRUE) 
    WITH CHECK (TRUE);

-- ========================================
-- 트리거: text_content updated_at 자동 갱신
-- ========================================
CREATE OR REPLACE FUNCTION public.update_text_content_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_tc_updated_at
    BEFORE UPDATE ON public.text_content
    FOR EACH ROW
    EXECUTE FUNCTION public.update_text_content_updated_at();






-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                       2. TEXT_CONTENT 관련 함수                            ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * FUNCTION: 텍스트 데이터 Upsert
 ***********************************************************************************************
 * 설명: 텍스트 콘텐츠를 text_content 테이블에 저장
 * 용도: 사용자 입력 또는 크롤링 데이터 저장
 * 
 * 특이사항:
 *   - hash_key는 클라이언트에서 SHA256으로 생성해서 전달
 *   - char_count, word_count, line_count도 클라이언트에서 계산해서 전달
 * 
 * 반환: {success, id, hash_key}
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.upsert_text_content(
    p_hash_key VARCHAR(64),
    p_content TEXT,
    p_title TEXT DEFAULT NULL,
    p_content_type VARCHAR(50) DEFAULT 'plain',
    p_language VARCHAR(10) DEFAULT NULL,
    p_source_url TEXT DEFAULT NULL,
    p_source_name VARCHAR(255) DEFAULT NULL,
    p_source_type VARCHAR(50) DEFAULT NULL,
    p_author_name VARCHAR(255) DEFAULT NULL,
    p_published_date TIMESTAMPTZ DEFAULT NULL,
    p_char_count INTEGER DEFAULT 0,
    p_word_count INTEGER DEFAULT 0,
    p_line_count INTEGER DEFAULT 0,
    p_metadata_json JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    -- 필수 파라미터 체크
    IF p_hash_key IS NULL OR p_hash_key = '' THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'hash_key is required'
        );
    END IF;
    
    IF p_content IS NULL OR LENGTH(TRIM(p_content)) = 0 THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'content is required and cannot be empty'
        );
    END IF;

    -- Upsert
    INSERT INTO public.text_content (
        hash_key,
        content,
        title,
        content_type,
        language,
        source_url,
        source_name,
        source_type,
        author_name,
        published_date,
        char_count,
        word_count,
        line_count,
        metadata_json,
        last_processed_at
    ) VALUES (
        p_hash_key,
        p_content,
        p_title,
        p_content_type,
        p_language,
        p_source_url,
        p_source_name,
        p_source_type,
        p_author_name,
        p_published_date,
        p_char_count,
        p_word_count,
        p_line_count,
        p_metadata_json,
        NOW()
    )
    ON CONFLICT (hash_key) DO UPDATE SET
        content = EXCLUDED.content,
        title = COALESCE(EXCLUDED.title, public.text_content.title),
        content_type = EXCLUDED.content_type,
        language = COALESCE(EXCLUDED.language, public.text_content.language),
        source_url = COALESCE(EXCLUDED.source_url, public.text_content.source_url),
        source_name = COALESCE(EXCLUDED.source_name, public.text_content.source_name),
        source_type = COALESCE(EXCLUDED.source_type, public.text_content.source_type),
        author_name = COALESCE(EXCLUDED.author_name, public.text_content.author_name),
        published_date = COALESCE(EXCLUDED.published_date, public.text_content.published_date),
        char_count = EXCLUDED.char_count,
        word_count = EXCLUDED.word_count,
        line_count = EXCLUDED.line_count,
        metadata_json = COALESCE(EXCLUDED.metadata_json, public.text_content.metadata_json),
        last_processed_at = NOW()
    RETURNING id INTO v_id;

    RETURN jsonb_build_object(
        'success', true,
        'id', v_id,
        'hash_key', p_hash_key
    );
END;
$$;

COMMENT ON FUNCTION public.upsert_text_content IS 
'텍스트 콘텐츠를 text_content 테이블에 저장 (hash_key 기반 중복 방지)';


/*
 ***********************************************************************************************
 * FUNCTION: AI 분석 결과 저장
 ***********************************************************************************************
 * 설명: AI 분석 결과를 text_content 테이블의 ai_* 필드에 저장
 * 용도: AI 분석 완료 후 호출
 * 
 * 파라미터: 모든 파라미터는 선택적 (NULL이면 기존 값 유지)
 * 반환: {success, hash_key, places_count} 또는 {success: false, error}
 ***********************************************************************************************
 */
CREATE OR REPLACE FUNCTION public.upsert_text_content_ai_analysis(
    p_hash_key VARCHAR(64),
    p_ai_summary TEXT DEFAULT NULL,
    p_ai_key_points TEXT[] DEFAULT NULL,
    p_ai_meta_category TEXT[] DEFAULT NULL,
    p_ai_meta_influencer TEXT[] DEFAULT NULL,
    p_ai_meta_season TEXT[] DEFAULT NULL,
    p_ai_meta_time_of_day TEXT[] DEFAULT NULL,
    p_ai_meta_activity_type TEXT[] DEFAULT NULL,
    p_ai_meta_special_tag TEXT[] DEFAULT NULL,
    p_ai_meta_kpop TEXT[] DEFAULT NULL,
    p_ai_meta_target_age TEXT[] DEFAULT NULL,
    p_ai_meta_target_audience TEXT[] DEFAULT NULL,
    p_ai_meta_landmark TEXT[] DEFAULT NULL,
    p_ai_meta_city TEXT[] DEFAULT NULL,
    p_ai_meta_country TEXT[] DEFAULT NULL,
    p_ai_meta_district TEXT[] DEFAULT NULL,
    p_ai_meta_neighborhood TEXT[] DEFAULT NULL,
    p_ai_meta_place TEXT[] DEFAULT NULL,
    p_ai_places JSONB DEFAULT NULL,
    p_ai_model VARCHAR(50) DEFAULT NULL,
    p_ai_confidence NUMERIC(3,2) DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_places_count SMALLINT;
BEGIN
    -- hash_key 존재 확인
    IF NOT EXISTS (SELECT 1 FROM public.text_content WHERE hash_key = p_hash_key) THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'hash_key not found'
        );
    END IF;
    
    -- 장소 개수 계산 (있는 경우)
    v_places_count := CASE 
        WHEN p_ai_places IS NOT NULL 
        THEN jsonb_array_length(p_ai_places)::SMALLINT
        ELSE NULL
    END;
    
    -- AI 분석 결과 업데이트 (COALESCE로 NULL이면 기존 값 유지)
    UPDATE public.text_content SET
        ai_summary = COALESCE(p_ai_summary, ai_summary),
        ai_key_points = COALESCE(p_ai_key_points, ai_key_points),
        ai_meta_category = COALESCE(p_ai_meta_category, ai_meta_category),
        ai_meta_influencer = COALESCE(p_ai_meta_influencer, ai_meta_influencer),
        ai_meta_season = COALESCE(p_ai_meta_season, ai_meta_season),
        ai_meta_time_of_day = COALESCE(p_ai_meta_time_of_day, ai_meta_time_of_day),
        ai_meta_activity_type = COALESCE(p_ai_meta_activity_type, ai_meta_activity_type),
        ai_meta_special_tag = COALESCE(p_ai_meta_special_tag, ai_meta_special_tag),
        ai_meta_kpop = COALESCE(p_ai_meta_kpop, ai_meta_kpop),
        ai_meta_target_age = COALESCE(p_ai_meta_target_age, ai_meta_target_age),
        ai_meta_target_audience = COALESCE(p_ai_meta_target_audience, ai_meta_target_audience),
        ai_meta_landmark = COALESCE(p_ai_meta_landmark, ai_meta_landmark),
        ai_meta_city = COALESCE(p_ai_meta_city, ai_meta_city),
        ai_meta_country = COALESCE(p_ai_meta_country, ai_meta_country),
        ai_meta_district = COALESCE(p_ai_meta_district, ai_meta_district),
        ai_meta_neighborhood = COALESCE(p_ai_meta_neighborhood, ai_meta_neighborhood),
        ai_meta_place = COALESCE(p_ai_meta_place, ai_meta_place),
        ai_places = COALESCE(p_ai_places, ai_places),
        ai_places_count = COALESCE(v_places_count, ai_places_count),
        ai_model = COALESCE(p_ai_model, ai_model),
        ai_confidence = COALESCE(p_ai_confidence, ai_confidence),
        ai_analyzed_at = NOW(),
        last_processed_at = NOW()
    WHERE hash_key = p_hash_key;
    
    RETURN jsonb_build_object(
        'success', true,
        'hash_key', p_hash_key,
        'places_count', v_places_count
    );
END;
$$;

COMMENT ON FUNCTION public.upsert_text_content_ai_analysis IS 
'AI 분석 결과를 text_content 테이블의 ai_* 필드에 저장';


-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║                                                                           ║
-- ║                               3. 뷰 (VIEW)                                ║
-- ║                                                                           ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

/*
 ***********************************************************************************************
 * VIEW: 장소 검색용 뷰
 ***********************************************************************************************
 * 설명: ai_places JSONB를 행으로 펼쳐서 장소별 검색 가능하게 함
 * 용도: 특정 장소가 포함된 텍스트 검색
 * 
 * 쿼리 예시:
 *   SELECT * FROM text_content_places WHERE city = '서울';
 *   SELECT * FROM text_content_places WHERE place_name LIKE '%카페%';
 *   SELECT * FROM text_content_places WHERE place_type = 'restaurant';
 *   SELECT * FROM text_content_places WHERE country = 'KR' AND city = '부산';
 ***********************************************************************************************
 */
CREATE OR REPLACE VIEW public.text_content_places AS
SELECT 
    -- 텍스트 정보
    tc.id,
    tc.hash_key,
    tc.title,
    tc.content_type,
    tc.language,
    tc.source_name,
    tc.author_name,
    tc.created_at,
    tc.char_count,
    tc.word_count,
    
    -- 장소 기본 정보
    place.value->>'place_name' AS place_name,
    place.value->>'place_name_en' AS place_name_en,
    place.value->>'place_name_native' AS place_name_native,
    place.value->>'place_type' AS place_type,
    
    -- 위치 정보
    place.value->>'country' AS country,
    place.value->>'city' AS city,
    place.value->>'district' AS district,
    place.value->>'neighborhood' AS neighborhood,
    place.value->>'landmark' AS landmark,
    place.value->>'address' AS address,
    (place.value->>'latitude')::NUMERIC AS latitude,
    (place.value->>'longitude')::NUMERIC AS longitude,
    
    -- 시간 정보 (이벤트/축제용)
    place.value->>'period' AS period,
    place.value->>'start_date' AS start_date,
    place.value->>'end_date' AS end_date,
    place.value->>'operation_hours' AS operation_hours,
    
    -- 상세 정보
    place.value->'prices' AS prices,
    place.value->'recommend_menu' AS recommend_menu,
    place.value->'travel_tips' AS travel_tips,
    place.value->>'notice' AS notice,
    place.value->>'review_summary' AS review_summary,
    (place.value->>'reservation_required')::BOOLEAN AS reservation_required,
    
    -- 콘텐츠 내 위치
    (place.value->>'order_in_content')::INTEGER AS order_in_content
    
FROM public.text_content tc
CROSS JOIN LATERAL jsonb_array_elements(tc.ai_places) AS place(value)
WHERE tc.ai_places IS NOT NULL 
    AND tc.is_active = TRUE 
    AND tc.is_deleted = FALSE;
